### ISSUE TITLE
SDK: supported versions of Ruby

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#10]
What versions/implementations of Ruby should we support?
* MRI 2.5.0 and newer? In general, N-1?
* JRuby?
* Graal/Truffle?

**Comment by indrekj** [comment]
In MRI case probably same as in https://www.ruby-lang.org/en/downloads/branches/ `normal maintenance`, maybe `security maintenance` as well. Don't really see a point supporting versions that are not supported by the ruby-core team.

**Comment by fbogsany** [comment]
+1 for `normal maintenance` for MRI

**Comment by luong-komorebi** [comment]
+1 for security maintenance for MRI. For JRuby and Grall, let's consider them later since they already have the capability of running java code from Ruby 
https://github.com/oracle/truffleruby/blob/master/doc/user/jruby-migration.md#using-java-from-ruby
https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby

**Comment by fbogsany** [comment]
Shopify has a need to support both JRuby and TruffleRuby. The former is already targeted by CI. I’ll add TruffleRuby as well.

**Comment by fbogsany** [comment]
We've enabled CI for JRuby, TruffleRuby, and MRI 2.4 - 2.6. This is currently run for Shopify PRs. Running for everyone is gated on #77. Closing this, though, since we've covered all the bases for now.

**Comment by duaneking** [comment]
With respect,  this is a bad policy that actively harms the ruby and open telemetry ecosystems, and makes it massively harder to do the due diligence required for updates and maintenance of legacy projects that you are explicating saying here you want to support upgrades to.
