### ISSUE TITLE
Documentation: Add design rationale to contributing guide

### ISSUE THREAD

**Issue by elskwid** [open-telemetry/opentelemetry-ruby#105]
Add any design rationale for standout differences between this (Ruby) and other libraries or the spec.

From @fbogsany 

> I've been thinking recently about the first one, since we have some distinct Ruby-isms in our codebase that differ significantly from other implementations.

**Comment by benedictfischer09** [comment]
I would like to work on this

**Comment by mwear** [comment]
Thanks. It's assigned @benedictfischer09!

**Comment by plantfansam** [comment]
Is this issue still relevant?
