### ISSUE TITLE
`all` gem missing runtime dependency on `aws_sdk`

### ISSUE THREAD

**Issue by vreynolds** [open-telemetry/opentelemetry-ruby#1053]
**Description of the bug**

Adding just the following gems to my app:

```
gem "opentelemetry-api"
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-all"
```

and attempting to initialize OTEL:

```ruby
require 'opentelemetry/sdk'
require 'opentelemetry/exporter/otlp'
require 'opentelemetry/instrumentation/all'
require 'rubygems'

OpenTelemetry::SDK.configure do |c|
  c.use_all()
end
```

results in the following error:

```shell
/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- opentelemetry-instrumentation-aws_sdk (LoadError)
```

Adding this to the app Gemfile fixes the error:

```
gem "opentelemetry-instrumentation-aws_sdk"
```

**Share details about your runtime**

Operating system details: MacOS 11.6.1
RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.2", "3.0.0"
RUBY_DESCRIPTION:

**Comment by arielvalentin** [comment]
cc: @YanivD

**Comment by YanivD** [comment]
@arielvalentin thanks for the mention! 
Created PR https://github.com/open-telemetry/opentelemetry-ruby/pull/1054 to resolve this issue

**Comment by arielvalentin** [comment]
Thank you @YanivD for quick turn around time ✨

**Comment by stympy** [comment]
Could we get a release of the gem? Since there hasn't been one since this was merged, new users (like me 😁) are still encountering this error.
