### ISSUE TITLE
[Instrumentation Base] Improve install failure messages

### ISSUE THREAD

**Issue by robertlaurin** [open-telemetry/opentelemetry-ruby#1055]
Follow up form this discussion https://github.com/open-telemetry/opentelemetry-ruby/discussions/1050, there is value in improve the quality of the failure to install messages.  We could increase the detail to identify which specific checks failed to provide a better set of bread crumbs for users to follow in the event they have instrumentation failing to install.

**Comment by ahayworth** [comment]
@NickLarsenNZ unfortunately we don't yet have better logging in this area yet. And, even more unfortunately, the minimum supported Rails version is now Rails 6 (since Rails 5 went EOL last summer): https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/307

**Comment by TDkekai** [comment]
I am using Roda, and have this error: `OpenTelemetry::Instrumentation::Mongo failed to install`, anyone know why ?
