### ISSUE TITLE
Documentation: Add links or information on style to contributing

### ISSUE THREAD

**Issue by elskwid** [open-telemetry/opentelemetry-ruby#106]
Add links or information on style: commits, language, etc.

Include usage of any automated tools like `RuboCop`.

**Comment by plantfansam** [comment]
We [specify](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/CONTRIBUTING.md#make-your-modifications) that we want Conventional Commits and use Rubocop in `contributing.md` now, so I think we can close this one. Please reopen if you disagree!
