### ISSUE TITLE
ActiveRecord Instrumenter Argument Error 

### ISSUE THREAD

**Issue by thetizzo** [open-telemetry/opentelemetry-ruby#1062]
**Description of the bug**

Hi 👋,

I am implementing OpenTelemetry on a Rails app and ran into a conflict between the OTel ActiveRecord Instrumenter and [this gem we are using for upserts with ActiveRecord](https://rubygems.org/gems/active_record_upsert).

The OTel AR instrumenter has a patch that matches the method signature of the Rails `upsert` method, like this:
```ruby 
def upsert(attributes, returning: nil, unique_by: nil)
  tracer.in_span("#{self}.upsert") do
    super
  end
end
```
[Link to code](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/patches/persistence_insert_class_methods.rb#L46-L50)

This passes along `returning` and `unique_by` in the arguments to the method called by `super`.  In our case, since we are using a different implementation of `upsert` that doesn't expect these same arguments, this throws an `ArgumentError`.

However, since the instrumenter doesn't use any of these args other than to pass them along, I'm wondering if it shouldn't explicitly name any arguments in the method signature above and thus avoid changing the args that are being passed through like this:
```ruby
def upsert(**)
  tracer.in_span("#{self}.upsert") do
    super
  end
end
```

I tried this out on our app and it seems to resolve this issue.  

If this makes sense I think it is probably a good idea to update all the patches in this instrumenter that don't already use `**` to this style because it seems like the instrumenter should never change anything about how a method is called downstream.

If everyone agrees, I would be happy to open a PR for these updates. 😄 

**Share details about your runtime**

Operating system details: MacOS 11.6.1
RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.5"
RUBY_DESCRIPTION: "ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]"

**Share a simplified reproduction if possible**

I created an [example Rails app](https://github.com/thetizzo/otel_upsert_example) that demonstrates the issue.  It will require Postgres (because `upsert`) but you can clone it, run `rails db:create db:migrate`, then `rails test --backtrace` and it should fail the test with the `ArgumentError` as mentioned above.

**Comment by thetizzo** [comment]
It appears that this issue is solved in #1043 so when that PR gets merged and release, it should also resolve this issue!

**Comment by arielvalentin** [comment]
Thank you for your patience @thetizzo !

**Comment by thetizzo** [comment]
No problem!  Thanks for all the hard work, waiting is the easy part :D

**Comment by SomalianIvan** [comment]
Hey @thetizzo, we merged https://github.com/open-telemetry/opentelemetry-ruby/pull/1043. I think we can close this close this issue?

**Comment by thetizzo** [comment]
@SomalianIvan I do think we can close this since the other PR is merged.  However there doesn't seem to be a new release of the ActiveRecord instrumentation gem to make this change available for use.  Is there a plan for that?
