### ISSUE TITLE
Documentation: Add how to for bug reports

### ISSUE THREAD

**Issue by elskwid** [open-telemetry/opentelemetry-ruby#107]
Add a how to for submitting bug reports. This could be in the readme, contributing, or other documentation location.

**Comment by fhwang** [comment]
@fbogsany I can take this 🙋

**Comment by fbogsany** [comment]
Thanks @fhwang - I've assigned this to you.

**Comment by fhwang** [comment]
Are there any projects that we would consider a good model for a bug report template?
