### ISSUE TITLE
Incorrect default url for OTLP HTTP

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-ruby#1078]
While doing our due diligence before the 1.0 OTLP Trace Exporter release for JS we noticed that not all exporter implementations follow spec.

[Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/8e29f555b2282a3883b1b57009ad4eb11bfc5228/specification/protocol/exporter.md#configuration-options) states OTLP HTTP should use `http://localhost:4318` by default.

Ruby is using `https://localhost:4318/v1/traces` (https should be http): [link](https://github.com/open-telemetry/opentelemetry-ruby/blob/46020cc0ab9826b362854a6a913f30996ac528a2/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L47)

**Comment by arielvalentin** [comment]
Thanks for the report @dyladan!

Do you have availability to open a PR with a fix?

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/2014 changed the default from `https` to `http`.

**Comment by fbogsany** [comment]
There are probably other discrepancies in the exporter configuration we should look at. I don't think we've kept a close eye on the spec evolution since the original implementation of the exporter.

For example, there is some remaining work from https://github.com/open-telemetry/opentelemetry-ruby/pull/277#issuecomment-689232860 to rename the gem and add support for the `OTEL_EXPORTER_OTLP_PROTOCOL` environment variable.

**Comment by fbogsany** [comment]
Correct handling of `OTEL_EXPORTER_OTLP_ENDPOINT` vs `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` is a source of confusion. While the default value for `OTEL_EXPORTER_OTLP_ENDPOINT` is specced as `http://localhost:4318`, the signal specific path (`v1/traces`) is required to be appended to that value to produce the URL to be used by the exporter. The default value from https://github.com/open-telemetry/opentelemetry-ruby/blob/46020cc0ab9826b362854a6a913f30996ac528a2/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L47 passes unmodified through https://github.com/open-telemetry/opentelemetry-ruby/blob/46020cc0ab9826b362854a6a913f30996ac528a2/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L57-L61

My reading of the spec is that "default value" implies "default value assumed for `OTEL_EXPORTER_OTLP_ENDPOINT` if neither environment variable is present".

We could potentially restructure the code to make spec conformance clearer. Spec conformance for explicitly set `OTEL_EXPORTER_OTLP_ENDPOINT` is asserted here: https://github.com/open-telemetry/opentelemetry-ruby/blob/a8a596fbac5b0c565063179be8d1ce91f9e2dcdd/exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb#L65-L84
and spec conformance for the default `OTEL_EXPORTER_OTLP_ENDPOINT` value is asserted here: https://github.com/open-telemetry/opentelemetry-ruby/blob/a8a596fbac5b0c565063179be8d1ce91f9e2dcdd/exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb#L14-L27
although as mentioned, we haven't implemented the `https` -> `http` change from https://github.com/open-telemetry/opentelemetry-specification/pull/2014

**Comment by fbogsany** [comment]
I think the only change required here is to change the default to `http`.
