### ISSUE TITLE
OTEL Exporter environment variables for Grafana Cloud Tempo

### ISSUE THREAD

**Issue by satya0429** [open-telemetry/opentelemetry-ruby#1085]
Hi Team,

Spent good amount to find any useful information on OTEL Exporter environment variables for Grafana Cloud Tempo and unfortunately I cannot find one example of an OTEL endpoint that requires authentication.

Need some info that how can I pass environment varibales ?

OTEL_EXPORTER_OTLP_ENDPOINT 
**Endpoint:** tempo-us-central1.grafana.net:443
**Tempo URL:** https://tempo-us-central1.grafana.net/tempo
**User:** 141540
**Password:** <API Key>

**Comment by arielvalentin** [comment]
We support standard OTEL environment variables for configuration however we do not provide guidance for vendor specific configuration, authz, or authz. 

I recommend that you contact the Grafana Cloud team for support.

**Comment by jmarbach** [comment]
Hey @satya0429, and for anyone else reading, Grafana Cloud has provided updated documentation for writing data directly from the OpenTelemetry SDK: https://grafana.com/docs/grafana-cloud/data-configuration/otlp/send-data-otlp/#push-directly-from-applications-using-the-opentelemetry-sdks

In summary, three ENV vars are required to be set in your application:
`OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_ENDPOINT`, and `OTEL_EXPORTER_OTLP_HEADERS`

For example:

```
export OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
export OTEL_EXPORTER_OTLP_ENDPOINT="https://otlp-gateway-<region>.grafana.net/otlp"
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic <base64-encoded token built from your instance_id:api_key values>"
```

Please note that not all Grafana Cloud Tempo instances currently support being able to ingest traces directly from the OpenTelemetry SDK: https://grafana.com/docs/grafana-cloud/data-configuration/otlp/send-data-otlp/#before-you-begin

Finally, here's additional documentation on the OpenTelemetry SDK exporter configuration: https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/

**Comment by ahayworth** [comment]
@satya0429 Grafana does have documentation [here](https://grafana.com/docs/grafana-cloud/data-configuration/otlp/send-data-otlp/#push-directly-from-applications-using-the-opentelemetry-sdks) for pushing data directly from OTel SDKs with authentication. The environment variables referenced there are in fact [standard OTel environment variables](https://opentelemetry.io/docs/reference/specification/protocol/exporter/), which as @arielvalentin pointed out - the Ruby SDK does fully support. Should you choose to do so, you should be able to set those environment variables for your application to push traces directly to Tempo in Grafana Cloud.

However, as @arielvalentin also mentioned - that is typically where our support would end, unless there was some bug in the Ruby SDK related to supporting those headers. And, as @jmarbach mentioned - using some kind of local agent to buffer the traces locally for export will likely be a much better experience than having your application push _directly_ to Tempo. Personally, I recommend following their advice! 😄 ❤️ 

I'm going to close this issue out, but please feel free to open another issue (or a discussion!) or chat with us in slack if you have any problems with the SDK itself. We're happy to help you use it!
