### ISSUE TITLE
[AWS SDK Instrumentation] Trace does not report HTTP status in attributes

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/opentelemetry-ruby#1094]
## Description

I was using the `opentelemetry-ruby` SDK to instrument my call to S3 using the `opentelemetry-instrumentation-aws_sdk` gem. I noticed that the populated attributes are as follows:

```ruby
#<struct OpenTelemetry::SDK::Trace::SpanData name="S3.ListBuckets",
kind=:client,
status=
#<OpenTelemetry::Trace::Status:0x00007f9b14253508 @code=1, @description="">,
parent_span_id="\xA1\xA7\x11\xB0\xAEGp\xC5",
total_recorded_attributes=4,
total_recorded_events=0,
total_recorded_links=0,
start_timestamp=1642709302898094000,
end_timestamp=1642709303152641000,
attributes=
 {"aws.region"=>"us-west-2",
  "rpc.system"=>"aws-api",
  "rpc.method"=>"ListBuckets",
  "rpc.service"=>"S3"}, # <- no http.status
```

I noticed that the `attributes` did not have the `http.status` attribute set. In the `opentelemetry-instrumentation-aws_lambda` gem we should be able to popoulate this attribute using `meatadata` from the AWS SDK response here:

https://github.com/open-telemetry/opentelemetry-ruby/blob/f0593e7d97c62b10862c382d14f533dbc49be580/instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/handler.rb#L40-L42

We do [something similar in the OTel Python Instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/dd72d94615a66105a5275efac08f1fd5c89c54b2/instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/__init__.py#L263-L265) of the AWS SDK:

```pythonresult = None
try:
    result = original_func(*args, **kwargs)
    _apply_response_attributes(span, result)

...

metadata = result.get("ResponseMetadata")

...

status_code = metadata.get("HTTPStatusCode")

if status_code is not None:
    span.set_attribute(SpanAttributes.HTTP_STATUS_CODE, status_code)
```

If this makes sense I can add a PR to populate this attribute 🙂 There might some small differences in AWS SDK Ruby, but should still be accessible.

Thanks.

**Comment by arielvalentin** [comment]
> If this makes sense I can add a PR to populate this attribute 🙂 There might some small differences in AWS SDK Ruby, but should still be accessible.

@NathanielRN contributions are welcome!

**Comment by ericmustin** [comment]
Is this present on the underlying HTTP instrumentation client span? Maybe the issue here is that the aws-sdk instrumentation doesn't `enrich` the downstream http span, but instead generates another layer.

**Comment by NathanielRN** [comment]
@ericmustin 

> Is this present on the underlying HTTP instrumentation client span? Maybe the issue here is that the aws-sdk instrumentation doesn't enrich the downstream http span, but instead generates another layer.

I can post the entire console log output here for your reference! Not sure about "enriching" a downstream span... but the information _is_ available from a "AWS Ruby SDK" viewpoint and we should probably take advantage of asking the AWS SDK what it thinks the response code should be when setting it on what is supposed to be the "AWS SDK span". I see an `http.status_code = 200` but that's for my Rails server request. Let me know if that makes sense! I posted a PR that hopefully solves this issue.

```
Processing by ApplicationController#aws_sdk_call as */*
#<struct OpenTelemetry::SDK::Trace::SpanData
 name="S3.ListBuckets",
 kind=:client,
 status=
  #<OpenTelemetry::Trace::Status:0x00007fcd342afc70 @code=1, @description="">,
 parent_span_id="7\xCC7)v\xE5#m",
 total_recorded_attributes=4,
 total_recorded_events=0,
 total_recorded_links=0,
 start_timestamp=1642723862714061000,
 end_timestamp=1642723862968598000,
 attributes=
  {"aws.region"=>"us-west-2",
   "rpc.system"=>"aws-api",
   "rpc.method"=>"ListBuckets",
   "rpc.service"=>"S3"},
 links=nil,
 events=nil,
 resource=
  #<OpenTelemetry::SDK::Resources::Resource:0x00007fcd31fc1858
   @attributes=
    {"service.name"=>"aws-otel-manual-rails-sample",
     "process.pid"=>20334,
     "process.command"=>"bin/rails",
     "process.runtime.name"=>"ruby",
     "process.runtime.version"=>"2.7.5",
     "process.runtime.description"=>
      "ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]",
     "telemetry.sdk.name"=>"opentelemetry",
     "telemetry.sdk.language"=>"ruby",
     "telemetry.sdk.version"=>"1.0.2"}>,
 instrumentation_library=
  #<struct OpenTelemetry::SDK::InstrumentationLibrary
   name="OpenTelemetry::Instrumentation::AwsSdk",
   version="0.1.0">,
 span_id="\xCD\xCF\xD6\xFCOr\x19\xF8",
 trace_id="a\xE9\xFA\x16\xA1>\xCD\"vB\xA3\xF27a\xDD\xB6",
 trace_flags=#<OpenTelemetry::Trace::TraceFlags:0x00007fcd354b56e0 @flags=1>,
 tracestate=#<OpenTelemetry::Trace::Tracestate:0x00007fcd354ac798 @hash={}>>
Completed 200 OK in 280ms (Views: 0.2ms | Allocations: 32415)


#<struct OpenTelemetry::SDK::Trace::SpanData
 name="ApplicationController#aws_sdk_call",
 kind=:server,
 status=
  #<OpenTelemetry::Trace::Status:0x00007fcd342afc70 @code=1, @description="">,
 parent_span_id="\x00\x00\x00\x00\x00\x00\x00\x00",
 total_recorded_attributes=6,
 total_recorded_events=0,
 total_recorded_links=0,
 start_timestamp=1642723862535508000,
 end_timestamp=1642723862973336000,
 attributes=
  {"http.method"=>"GET",
   "http.host"=>"0.0.0.0:8080",
   "http.scheme"=>"http",
   "http.target"=>"/aws-sdk-call",
   "http.user_agent"=>"curl/7.64.1",
   "http.status_code"=>200},
 links=nil,
 events=nil,
 resource=
  #<OpenTelemetry::SDK::Resources::Resource:0x00007fcd31fc1858
   @attributes=
    {"service.name"=>"aws-otel-manual-rails-sample",
     "process.pid"=>20334,
     "process.command"=>"bin/rails",
     "process.runtime.name"=>"ruby",
     "process.runtime.version"=>"2.7.5",
     "process.runtime.description"=>
      "ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]",
     "telemetry.sdk.name"=>"opentelemetry",
     "telemetry.sdk.language"=>"ruby",
     "telemetry.sdk.version"=>"1.0.2"}>,
 instrumentation_library=
  #<struct OpenTelemetry::SDK::InstrumentationLibrary
   name="OpenTelemetry::Instrumentation::Rack",
   version="0.20.1">,
 span_id="7\xCC7)v\xE5#m",
 trace_id="a\xE9\xFA\x16\xA1>\xCD\"vB\xA3\xF27a\xDD\xB6",
 trace_flags=#<OpenTelemetry::Trace::TraceFlags:0x00007fcd354b56e0 @flags=1>,
 tracestate=#<OpenTelemetry::Trace::Tracestate:0x00007fcd354ac798 @hash={}>>
```

**Comment by YanivD** [comment]
@NathanielRN thanks for creating the PR with the requested change.

IMO `http.status` attribute belongs to the child HTTP span. From the SDK client point of view, the request can success or fail, and if I remember correctly the http status code is not returned from the SDK library when using it.
On the other hand, I can see how this attribute might be meaningful in some cases and I think we can add it also for the AWS SDK span.

**Comment by NathanielRN** [comment]
@YanivD thanks for your feedback!

I can totally see this being useful to the child HTTP span, but on the other hand, users seem to treat AWS SDK as the terminal node in tracing. Even the [OTel Ruby Docs for the AWS SDK Instrumentation](https://github.com/open-telemetry/opentelemetry-ruby/tree/main/instrumentation/aws_sdk#usage) suggest you use the instrumentation with `suppress_instrumentation: true`. This would eliminate the HTTP child span if I understand correctly?

In our service, we’ve found this attribute valuable. The HTTP status code can be used a lot by the backend to customize the visualization. At AWS, we have [CI tests to make sure this value shows up across several OTel language](https://github.com/aws-observability/aws-otel-test-framework/blob/bf2b8fa449be00065a26a63a45dc94b7279b52be/validator/src/main/resources/expected-data-template/otelSDKexpectedAWSSDKTrace.mustache#L21) which is what prompted the change. We were thinking of making an exception in https://github.com/aws-observability/aws-otel-test-framework/pull/522 but thought instead we could just contribute the change upstream right away 🙂

I can also see it being useful for filtering  through AWS SDK spans in the backend by status code.

Finally, I think this span is the right place for it because at the end of the day it is still metadata populated by the AWS SDK itself, not necessarily by the underlying HTTP client used. In this way our instrumentation will be enhanced because it provides insight into what AWS SDK itself thinks about the result and makes that information available to the user in the trace which they normally would have to jump through hoops to go access.

Please let me know what you think! Happy to discuss whatever we can to move this along 🙂

**Comment by YanivD** [comment]
> Even the OTel Ruby Docs for the AWS SDK Instrumentation suggest you use the instrumentation with `suppress_instrumentation: true`. This would eliminate the HTTP child span if I understand correctly?

You understand it correctly.

I thing we can move on with this change and add `http.status` 🙂

**Comment by YanivD** [comment]
@NathanielRN 
I'm adding `http.status_code` also for JS instrumentation 🥳
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/844
