### ISSUE TITLE
Missing resource detector for Google Cloud Functions

### ISSUE THREAD

**Issue by khyatigandhi6** [open-telemetry/opentelemetry-ruby#1124]
There is already support for resource detection of Google Compute Engine(gce) and Google Kubernetes Engine(gke).
But, resource detection for google cloud function is missing as part of GCP.

I would be happy to contribute if this requirement is valid and needs work.

**Comment by ericmustin** [comment]
@khyatigandhi6 Hey, for sure I think GCP Cloud Function Resource Detection would be valuable, internally we aren't really users of GCP Cloud Functions so this isn't a huge priority for myself or the maintainers, but definitely be happy to take a PR.

Some suggestions:
- Are you aware of another OpenTelemetry SDK in another language that provides this at the moment? If so i'd try to model after their approach for what resource attributes to collect and what to name them.
- I believe GCP Cloud Functions would fall under the `faas` semantic conventions in the OpenTelemetry Specification, so I'd use that as a guide for what attributes are required (if possible, if they arent available that's probably ok as this is still considered experimental) https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md
- If you choose to bake this logic into the existing codepath of GCP Resource Detector, in the event the environment detected is not a GCP Cloud Function, ideally there wouldn't be any side effects on existing users, ideally avoiding any extra compute or memory usage as well if possible.

Let me know if you're up for taking on this PR (No rush or anything) and i'd be happy to assign it to you. :)

**Comment by khyatigandhi6** [comment]
Hi @ericmustin,
As far as I checked, it is not present in any other languages of OpenTelemetry SDKs. We can definitely take the reference from `faas` semantic conventions.
I would like to work on this PR. I was thinking to include the logic in the existing GCP resource detector based on the environment check.

**Comment by ericmustin** [comment]
Assigned to you, thanks!
