### ISSUE TITLE
spec update: InstrumentationLibrary/InstrumentationScope

### ISSUE THREAD

**Issue by robbkidd** [open-telemetry/opentelemetry-ruby#1126]
https://github.com/open-telemetry/opentelemetry-proto/pull/362

**Comment by ahayworth** [comment]
Spec update in: https://github.com/open-telemetry/opentelemetry-specification/pull/2276

**Comment by ahayworth** [comment]
Per @robbkidd, it would be best if we bumped otel proto and implemented this at the same time, to avoid breaking things with Honeycomb. Seems like a kind thing to do, so we shall.
