### ISSUE TITLE
PG Instrumentation: Invalid span attribute value type Arel::Nodes::SqlLiteral

### ISSUE THREAD

**Issue by danielmbarlow** [open-telemetry/opentelemetry-ruby#1139]
## Problem 
Our logs are filled with errors like this:

```
OpenTelemetry error: invalid span attribute value type Arel::Nodes::SqlLiteral for key 'db.statement' on span 'SELECT <database name here>'
```
I expected to just see the statement in the trace (in Jaeger in our case), but it seems to be excluded.

### Runtime
```
ruby -v
=> ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
```

## How to reproduce
This works:
```
ApplicationRecord.connection.execute("Select 'test'")
```

In Jaeger we get:
![image](https://user-images.githubusercontent.com/7119502/156595470-001c0b06-da65-4ab2-9a5d-28fbccb6f791.png)

This doesn't work:
```
# This is valid code and executes the statement fine
ApplicationRecord.connection.execute(Arel.sql("Select 'test'"))
=> {"?column?"=>"test"}

# ... but console logs show this
=> E, [2022-03-03T16:25:32.573458 #52] ERROR -- : OpenTelemetry error: invalid span attribute value type Arel::Nodes::SqlLiteral for key 'db.statement' on span 'SELECT ***REDACTED**'
```

In Jaeger the `db.statement` tag is missing:

![image](https://user-images.githubusercontent.com/7119502/156596509-d4399a6a-f10a-48e0-bcb9-2508124bba26.png)

### Potential solution 

Maybe the gem could be changed to use `#to_s`:
```
Arel.sql("Select 'test'").to_s
=> "Select 'test'"
```

### Potential Workarounds
* Perhaps use `db_statement: :omit` to reduce log noise
* Use `#to_s` everywhere

**Comment by ericmustin** [comment]
Thanks for the report @danielmbarlow.

It looks like this is the problematic line in our PG instrumentation https://github.com/open-telemetry/opentelemetry-ruby/blob/ad51972e9bdc8ead0e69642056a4935683464dfc/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb#L87

We expect `sql` passed into the connection_adapters `execute` method to be a string type, [here](https://github.com/rails/rails/blob/645239817d15c36ff008ccb5b6c8887e3b2c8f4b/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L39-L51) (_which then invokes [`async_exec`](https://github.com/rails/rails/blob/645239817d15c36ff008ccb5b6c8887e3b2c8f4b/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L48),  which is [what we instrument](https://github.com/open-telemetry/opentelemetry-ruby/blob/ad51972e9bdc8ead0e69642056a4935683464dfc/instrumentation/pg/lib/opentelemetry/instrumentation/pg/constants.rb#L98)_).

But instead it's being passed a `Arel::Nodes::SqlLiteral` type (which is what's returned by `Arel#sql`, it would seem).

I have to investigate what the expected types are for the 1st argument in the connection_adapters `execute` method. I think if this is a valid argument type, we should attempt to be more defensive here, and ideally make some attempt to generate a [valid span attribute value](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attribute) value from the passed in argument

> A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.

It's possible this issue would also impact our mysql2 and trilogy instrumentation as well (i havent looked into those instrumentations too closely yet).

I'll update this issue when i have more information.
