### ISSUE TITLE
Documentation: Update with explanations of Tracer methods

### ISSUE THREAD

**Issue by elskwid** [open-telemetry/opentelemetry-ruby#123]
Update the documentation with [comments from @fbogsany](https://github.com/open-telemetry/opentelemetry-ruby/pull/118#issuecomment-542497023) during the review of #118.

**Comment by duonoid** [comment]
I can work on this.

**Comment by mwear** [comment]
Thanks for volunteering @duonoid. I went ahead and assigned the issue to you.
