### ISSUE TITLE
Support `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT` and `OTEL_ATTRIBUTE_COUNT_LIMIT`

### ISSUE THREAD

**Issue by ahayworth** [open-telemetry/opentelemetry-ruby#1251]
Added in https://github.com/open-telemetry/opentelemetry-specification/pull/1130

We were early adopters of some of these limits, but they are not formalized in the spec and we should update.

**Comment by fbogsany** [comment]
We have the trace-specific versions of these (`OTEL_SPAN_ATTRIBUTE_...`), and they appear to be correct, according to the spec (the spec calls them "model-specific limits"). We just need to support the more general env vars (`OTEL_ATTRIBUTE_...`) as fallback options here: https://github.com/open-telemetry/opentelemetry-ruby/blob/113e5133afd7a42c30273d860330008c24530d6d/sdk/lib/opentelemetry/sdk/trace/span_limits.rb#L34-L40
