### ISSUE TITLE
Ensure we are returning no-op span according to clarified requirements

### ISSUE THREAD

**Issue by ahayworth** [open-telemetry/opentelemetry-ruby#1255]
I'm not sure if we're actually doing this right or not, I haven't stared at it long enough yet: https://github.com/open-telemetry/opentelemetry-specification/pull/2121

**Comment by fbogsany** [comment]
This only applies to the no-op API implementation in the absence of a SDK. Our implementation conforms to the spec: https://github.com/open-telemetry/opentelemetry-ruby/blob/113e5133afd7a42c30273d860330008c24530d6d/api/lib/opentelemetry/trace/tracer.rb#L50-L58.

**Comment by fbogsany** [comment]
Further clarification here: our API `Span` is implicitly non-recording, so if we have a valid `Span` in the context, we return it.

**Comment by ahayworth** [comment]
Fantastical. 😄
