### ISSUE TITLE
SDK/API packaging 

### ISSUE THREAD

**Issue by luvtechno** [open-telemetry/opentelemetry-ruby#13]
This is a follow-up from [a meeting on June 26th, 2019](https://docs.google.com/document/d/1D15bO8o340sQm2CVZiukEJuCO_XMMHKPuTznoEhyFqE/edit#).

We’ll need to decide how we’ll package/gemify API and SDK in the Ruby lib. [OpenTelemetry Language Library Design Principles](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/library-guidelines.md) describes requirements and expected usages of API and SDK respectively. 

Look at how SIGs of other dynamic programming languages approach like Python and probably JavaScript.

**Comment by elskwid** [comment]
Given that we have the `gemspec` files for each gem, is this issue resolved? @fbogsany, @mwear Is this something other than configuring the gems?

**Comment by fbogsany** [comment]
I think this is done.
