### ISSUE TITLE
Add simple HTTP client/server example

### ISSUE THREAD

**Issue by elskwid** [open-telemetry/opentelemetry-ruby#130]
As part of #97, add an example in the same style as the `http` example in the [Go library](https://github.com/open-telemetry/opentelemetry-go/tree/master/example/http).

This should be a simple client/server all-in-one example with a corresponding docker-compose service to ease startup and usage.

**Comment by elskwid** [comment]
I'm getting ready to submit a PR for this! 🆘

**Comment by fbogsany** [comment]
Done in #131
