### ISSUE TITLE
Update to latest rubocop

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby#1321]
Our various gems are on a pretty old version of Rubocop (see @dazuma's comment [here](https://github.com/open-telemetry/opentelemetry-ruby/pull/1096#issuecomment-1018193322) for context). The SDK gem is at [`0.73.0`](https://github.com/open-telemetry/opentelemetry-ruby/blob/e533817ba387bbfd6270e5c4d0ae42452dd7d9dc/sdk/opentelemetry-sdk.gemspec#L46). We should update to the latest rubocop.

Now that instrumentation has been moved to `-contrib`, this should be a lighter lift.

- [x] API
- [ ] Common
- [ ] SDK
- [ ] Exporters
- [ ] Propagators
- [ ] Registry
- [ ] Semantic conventions

**Comment by richardmcmillen** [comment]
@ahayworth thanks for the reviews on those PR's. I take note of your comment about not enabling cops by default. Would you be ok to have new cops enabled if it doesn't result in too many autofixes?

I also note this issue wishes to standardise some more: https://github.com/open-telemetry/opentelemetry-ruby/issues/1334
I am thinking upgrading gems individually first and then consolidating would be a reasonable approach to get there.

Looking at the current configuration there aren't many unique entries throughout the .rubocop.yml files.

```
grep --include='.rubocop.yml' -REho "^[A-Z][a-zA-Z/]+" | grep -v AllCops | sort | uniq -c | sort -r
  27 Metrics/AbcSize
  19 Metrics/LineLength
  19 Metrics/BlockLength
  17 Style/ModuleFunction
  17 Naming/FileName
  17 Metrics/ParameterLists
  17 Metrics/MethodLength
  17 Lint/UnusedMethodArgument
   7 Layout/LineLength
   5 Style/StringLiterals
   5 Style/StringConcatenation
   5 Style/FrozenStringLiteralComment
   5 Lint/MissingSuper
   5 Lint/ConstantDefinitionInBlock
   5 Bundler/OrderedGems
   4 Metrics/PerceivedComplexity
   4 Metrics/CyclomaticComplexity
   3 Style/MethodCallWithoutArgsParentheses
   3 Style/BlockDelimiters
   2 Metrics/ModuleLength
   2 Gemspec/RequireMFA
   1 Style/BracesAroundHashParameters
   1 Layout/TrailingWhitespace
   1 Layout/TrailingEmptyLines
   1 Layout/EmptyLinesAroundModuleBody
```

Those bottom Layout ones at least seem pretty benign and is perhaps something I would tend to just fix and remove the custom configuration for.

**Comment by ahayworth** [comment]
@richardmcmillen Yes, I think it's fine - like I said elsewhere we can always turn it back off if needed! 😄 

(My snarky comments were not intended to be blocking, I apologize for not making that clear ❤️ )

**Comment by jamiemccarthy** [comment]
Is there still interest in having this done? It might be a fun holiday/weekend project...
