### ISSUE TITLE
Question: Any way to capture memory usage?

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/opentelemetry-ruby#1338]
OTEL is great for tracing latency on given endpoints.

Is there any way to track **memory usage** as well, (as measured by net memory increase across the parent trace?) This would be very useful in shaking out memory-leaks.

**Comment by johnnyshields** [comment]
@plantfansam wonderful, I really appreciate the reply 👍 Will close this issue. I do think it's worth to bring this up with the governance committee for a unified approach to memory tracking.

**Comment by plantfansam** [comment]
@johnnyshields you got it! Thanks for the contribution!
