### ISSUE TITLE
`OTEL_EXPORTER_OTLP_ENDPOINT` env variable does not work with a trailing `/`

### ISSUE THREAD

**Issue by pkanal** [open-telemetry/opentelemetry-ruby#1340]
**Description of the bug**
When using the `OTEL_EXPORTER_OTLP_ENDPOINT` env variable, if the endpoint contains a trailing `/`, the final URL becomes `<endpoint>//v1/traces` instead of `<endpoint>/v1/traces` and traces are not sent to the expected place. Other OTel exporter libraries (e.g. [Python](https://github.com/open-telemetry/opentelemetry-python/blob/dbcec9f3b143e4de424c16be9ecd19a16be3e630/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L181), [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/otlp-exporter-base/src/util.ts#L59)) handle endpoints with or without a trailing `/` so it would be good to keep it consistent with the Ruby exporter as well.

Here's a PR that makes a change to handle the trailing `/`: https://github.com/open-telemetry/opentelemetry-ruby/pull/1339

**Share details about your runtime**
Operating system details: MacOS Monterey 12.1
RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.2"
RUBY_DESCRIPTION: "ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin21]"

**Share a simplified reproduction if possible**
`OTEL_EXPORTER_OTLP_ENDPOINT` is set to `https://localhost:4318/` and so traces are being sent to `https://localhost:4318//v1/traces`

```rb
require 'opentelemetry/sdk'
require 'opentelemetry/exporter/otlp'
require 'opentelemetry/instrumentation/all'

  OpenTelemetry::SDK.configure do |c|
    c.service_name = ENV['SERVICE_NAME']

    # enable all auto-instrumentation available
    c.use_all()

    # add the Baggage and CarryOn processors to thepipeline
    c.add_span_processor(O11yWrapper::BaggageSpanProcessor.new)
    c.add_span_processor(O11yWrapper::CarryOnSpanProcessor.new)

    # Because we tinkered with the pipeline, we'll need to
    # wire up span batching and sending via OTLP ourselves.
    # This is usually the default.
    c.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        OpenTelemetry::Exporter::OTLP::Exporter.new()
      )
    )
  end
```

**Comment by robbkidd** [comment]
Closed by #1339 if someone With Power wishes to push to the Close button.
