### ISSUE TITLE
Best way to ignore/filter-out certain endpoints?

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/opentelemetry-ruby#1347]
I'm getting a lot of traces for endpoints such as `HealthController#index` (application heartbeat) which I'd like ignore.

What's the best way to do this?

**Comment by ahayworth** [comment]
@johnnyshields Assuming this is coming from a rack-based instrumentation, there are some options that can help out with this. The most straight-forward is likely the `untraced_endpoints` option, although there's also an option to pass a callable that makes the decision to trace or not - see the options [here](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/5d92b37671c59d8aff86d17e8661c3fc25da6a21/instrumentation/rack/lib/opentelemetry/instrumentation/rack/instrumentation.rb#L25-L32).

Additionally, you can pass this option in the environment - useful if you're relying on the rails instrumentation, which (depending on ordering) may make it difficult to specify the option: `export OTEL_RUBY_INSTRUMENTATION_RACK_CONFIG_OPTS="untraced_endpoints=/health,/ping"`

**Comment by ahayworth** [comment]
See also, some config examples here: https://github.com/open-telemetry/opentelemetry-ruby/discussions/640#discussioncomment-450437

**Comment by johnnyshields** [comment]
Thank you, I really appreciate it!
