### ISSUE TITLE
Crashing or Unstable OTEL collector causing the agent to hang

### ISSUE THREAD

**Issue by jdziat** [open-telemetry/opentelemetry-ruby#1436]
If you have an OTEL collector that is cycling or takes a long time to respond to trace pushes it can cause the entire application to grind to a halt.

Expected Behavior:
Should process traces separately from application logic so if it can't complete in a timely manner it doesn't impact application performance drastically.

**Comment by plantfansam** [comment]
Hi @jdziat, are you able to provide reproduction steps?

**Comment by jdziat** [comment]
If you could simulate a otel collector hanging on a connection i think that will reproduce it. I'll work on getting it to happen in a controlled environment.

**Comment by plantfansam** [comment]
Thanks @jdziat - highly appreciated!
