### ISSUE TITLE
ConsistentProbabilityBased sampler should pass through tracestate consistently

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#1448]
**Description of the bug**

`tracestate` is supposed to propagate through samplers, perhaps with updates, regardless of whether the parent context is valid. The `ConsistentProbabilityBased` sampler fabricates a new `tracestate` when the parent context is invalid: https://github.com/open-telemetry/opentelemetry-ruby/blob/24c8032ee51d092633d8e7125d3335b6ed80f998/sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_based.rb#L60-L67

The spec is not completely clear on this. The [documentation for Should Sample](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shouldsample) states:

> If the sampler returns an empty `Tracestate` here, the `Tracestate` will be cleared, so samplers SHOULD normally return the passed-in `Tracestate` if they do not intend to change it.

The [W3C Trace Context recommendation](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field) is more explicit:

> Vendors receiving a `tracestate` request header _MUST_ send it to outgoing requests. It _MAY_ mutate the value of this header before passing to outgoing requests. When mutating `tracestate`, the order of unmodified key/value pairs _MUST_ be preserved.

That said, though, there is some contradiction in later [description of the processing model](https://www.w3.org/TR/trace-context/#processing-model) that says:

> 3. If a `tracestate` header is received without an accompanying `traceparent` header, it is invalid and _MUST_ be discarded.

If the `traceparent` header is present, but invalid:

> the vendor creates a new `traceparent` header and deletes `tracestate`.

**Comment by plantfansam** [comment]
So I just wrote up a paragraph where I tried to restate the problem, reread it, and thought it was nonsense 😆, so I'll spare you. My general understanding: you perceive murkiness in the OpenTelemetry and W3C Trace Context specifications, specifically about `ConsistentProbabilitySampler#should_sample?`'s practice of minting a new `tracestate` when it sees an invalid span context (as when operating against the context of a root span). Is that right? 

Some stray thoughts from me grasping at comprehension:

- In the `ConsistentProbabilityBased` sampler, do we need to create a new `tracestate` if the parent span context is invalid? could we simply update the parent_span_context's associated tracestate, trusting that the propagator would drop invalid? 
- one _might_ argue that the w3c trace context specification pertains to transmitting trace context across process boundaries, so _perhaps_ the final 3 block quotes in your issue description are properly managed with propagators, rather than samplers.
- the practice of using the invalid span context to indicate a root span has confused me considerably. The CPS spec requires various things of [root spans](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/tracestate-probability-sampling.md#requirement-consistentprobabilitybased-sampler-sets-r-for-root-span) that seem at loggerheads with the w3c spec.

**Comment by fbogsany** [comment]
How do the existing samplers treat `tracestate`?

`ALWAYS_ON / ALWAYS_OFF` don't check validity of the parent context - they just pass through the incoming `tracestate`:
https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/samplers/constant_sampler.rb#L30

So does trace-id-ratio: https://github.com/open-telemetry/opentelemetry-ruby/blob/1ad4a212b5488dfdcec188640af4331756f35e12/sdk/lib/opentelemetry/sdk/trace/samplers/trace_id_ratio_based.rb#L31-L36

Parent-based does not touch `tracestate`: https://github.com/open-telemetry/opentelemetry-ruby/blob/1ad4a212b5488dfdcec188640af4331756f35e12/sdk/lib/opentelemetry/sdk/trace/samplers/parent_based.rb#L48-L56

The parent-consistent-probability sampler checks the parent span context validity, and sanitizes the `tracestate` if the context is valid, passing through everything other than the `ot` entry. If the context is _not_ valid, then the context is passed to the root sampler, without touching the `tracestate`: https://github.com/open-telemetry/opentelemetry-ruby/blob/1ad4a212b5488dfdcec188640af4331756f35e12/sdk_experimental/lib/opentelemetry/sdk/trace/samplers/parent_consistent_probability_based.rb#L42-L52

The consistent-probability sampler only uses the parent-context's `tracestate` if the parent span context is valid, otherwise it creates a completely new `tracestate`: https://github.com/open-telemetry/opentelemetry-ruby/blob/1ad4a212b5488dfdcec188640af4331756f35e12/sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_based.rb#L43-L67

**Comment by fbogsany** [comment]
Looking at the Go implementation of the default samplers, they all pass through the `tracestate` from the parent span context. They rely on `trace.SpanContextFromContext(ctx)` returning either a valid `SpanContext` or `noopSpan{}`, which has an empty `TraceState`. See https://github.com/open-telemetry/opentelemetry-go/blob/46f2ce5ca6adaa264c37cdbba251c9184a06ed7f/trace/context.go#L44-L61 and https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/sampling.go.

**Comment by fbogsany** [comment]
Java is curiously different. The (builtin) samplers do not return the `tracestate` with the result. Instead, the `SdkSpanBuilder` calls `getUpdatedTraceState` on the `SamplingResult`, unconditionally passing in the parent context's tracestate. The default implementation in `SamplingResult` simply returns its argument: https://github.com/open-telemetry/opentelemetry-java/blob/c201396f57b384436de63617af29424cb4a7e035/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/SamplingResult.java#L125-L136

See: https://github.com/open-telemetry/opentelemetry-java/blob/c201396f57b384436de63617af29424cb4a7e035/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java#L195C1-L202

**Comment by fbogsany** [comment]
The Java implementation of consistent probability sampling has a single implementation of `shouldSample` shared between several samplers. It unconditionally returns the parent context `tracestate` in the `SamplingResult`, with only the `ot` portion updated: https://github.com/open-telemetry/opentelemetry-java-contrib/blob/1f9784c18618ba09cff5eb95722b642373ec2a52/consistent-sampling/src/main/java/io/opentelemetry/contrib/sampler/consistent/ConsistentSampler.java#L294-L299

**Comment by fbogsany** [comment]
Go's implementation of consistent-probability sampling _also_ unconditionally passes through the parent context `tracestate` with only the `ot` portion updated: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/849072ef827b4abab754253e1e63e7b410a31084/samplers/probability/consistent/sampler.go#L127-L130

It is explicit about why this is done:
```go
        // Note: this ignores whether psc.IsValid() because this
        // allows other otel trace state keys to pass through even
        // for root decisions.
        state := psc.TraceState()
```
