### ISSUE TITLE
OTel SDK fails with `ThreadError` in `Signal.trap` blocks

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby#1449]
**Description of the bug**

Some systems at GitHub use `Signal.trap` HTTP requests to an internal exception reporting system, which uses `Net::HTTP` automatic instrumentation to trace the request:

```ruby
  # This must be called in the config/unicorn.rb after_fork hook to setup the
  # signal handling in the worker.
    trap 'USR2' do
      # send exception to failbot
      boom = WorkerTimeout.new('unicorn worker killed for taking too long')
      boom.backtrace = caller.dup
      Failbot::Rescuer.report(boom)
    end
```

However in CRuby `Mutex#sychronize` is prohibited  from being called in `Signal.trap` blocks per this issue: https://bugs.ruby-lang.org/issues/19473

That results in the following backtrace and causes our process to fail to complete the HTTP request:

```console
/vendor/gems/ruby/3.1.0/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/span.rb:237:in `synchronize': can't be called from trap context (ThreadError)
	from /vendor/gems/ruby/3.1.0/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/span.rb:237:in `finish'
	from /vendor/gems/ruby/3.1.0/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace/tracer.rb:35:in `in_span'
	from /vendor/gems/ruby/3.1.0/gems/opentelemetry-instrumentation-net_http-0.22.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:70:in `connect'
	from /usr/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
	from /usr/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
	from /usr/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
	from /vendor/gems/ruby/3.1.0/gems/opentelemetry-instrumentation-net_http-0.22.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:19:in `request'
```

I am not sure if we should be guarding for this in instrumentation or if we should rescue from `ThreadError` where we currently use `Mutex.synchronize`. At a minimum I think the SDK should not raise a `ThreadError` and allow instrumented libraries to work as usual.  

**Share details about your runtime**

Operating system details: Debian 11 (ruby:3.1.2-bullseye docker image)
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.1.2"

**Share a simplified reproduction if possible**

```rb
# coming soon! 
```
cc: @destinyharrell @offbyone

**Comment by arielvalentin** [comment]
Reposting what I shared with my colleagues:

> I was looking at Ruby Docs for Signal https://docs.ruby-lang.org/en/master/signals_rdoc.html#top
> 
> > Unsafe methods to call in [Signal.trap](https://docs.ruby-lang.org/en/master/Signal.html#method-c-trap) blocks
> > When in doubt, consider anything not listed as safe below as being unsafe.
> > 
> > Mutex#lock, Mutex#synchronize and any code using them are explicitly unsafe. This includes [Monitor](https://docs.ruby-lang.org/en/master/Monitor.html) in the standard library which uses Mutex to provide reentrancy.
> > 
> > [Dir.chdir](https://docs.ruby-lang.org/en/master/Dir.html#method-c-chdir) with block
> 
> As I mentioned in our slack thread, we cannot guarantee that calling Failbot.report will not use Mutex in the future to ensure thread safety and Failbot relies on a logger to output diagnostic messages, which is also known to cause issues because the device it is writing to may perform unsafe IO operations.
> 
> An option for you all to consider here may be to wrap any code you use in Faibot.report in pthread. In the section of the of the docs titled Commonly safe operations inside Signal.trap blocks, it states:
> 
> > Creating a new [Thread](https://docs.ruby-lang.org/en/master/Thread.html) via [Thread.new](https://docs.ruby-lang.org/en/master/Thread.html#method-c-new)/Thread.start can used to get around the unusability of Mutexes inside a signal handler
> 
> I am probably going to update the public docs on opentelemtry.io to remind/warn folks about this potential problem.

**Comment by arielvalentin** [comment]
What we've decided to do for the time being is spin off a thread to quarantine any interactions that _may_ generate spans. 

It adds some complexity so we're still testing it.

**Comment by robbkidd** [comment]
I did what I could to reproduce in [a gist](https://gist.github.com/robbkidd/eb2a5e57a6b6680bddbfa13d9a4b2990) an app that would have the missing spans from the default-aggressive KILL of timed out workers when using unicorn. The gist includes both changes that would need to be applied by operators: (1) the monkeypatch to unicorn's `murder_lazy_workers` method to send a distinct signal to workers _about_ to be KILLed and (2) a trap for that distinct signal in the application itself to catch it and tidy itself up before it shuffles off its mortal coil.

The unicorn project is [firmly against receiving a change upstream](https://yhbt.net/unicorn-public/20180224151559.GA15504@whir/) to add any timeout signaling prior to worker death, so we're left with documenting these workarounds to [Hail Mary](https://idioms.thefreedictionary.com/Hail+Mary) some telemetry from a dying worker so folks can find where their [timing problems are](https://yhbt.net/unicorn/Application_Timeouts.html).

**Comment by arielvalentin** [comment]
One thing I want to clarify about this report is that there are 2 issues in 1.

The primary problem I am reporting here is that the SDK used Mutexes to ensure thread safety, however CRuby prohibits the use of Mutexes in Signal.trap.

The SDK spec states that:

> OpenTelemetry implementations MUST NOT throw unhandled exceptions at run time

Any code that it auto instrumented and is executed in a trap block results in a ThreadError anytime you attempt to mutate a span. That causing the trap block not to run to completion and that is undesirable.

So what I'm saying here is we have a bug. The SDK is raising errors and it should not. 

The second problem of not missing spans on exit is not a bug it's an unpleasant experience. The SDK does not make guarantees about delivering spans or processing unfinished spans on exit/shutdown. That is unfortunate but it's not a bug.

I hope they clears it up a bit. I think we need to do something and handle thread errors and worry about the unfinished spans experience in a separate issue. 

Something to keep in mind that there are similar issue with using the Ruby Standard Logger so we should be careful about using logging to report the error as well.
