### ISSUE TITLE
Sidekiq integration

### ISSUE THREAD

**Issue by danielmbarlow** [open-telemetry/opentelemetry-ruby#151]
We are using OpenCensus to do this and have a [PR open on that project](https://github.com/census-instrumentation/opencensus-ruby/pull/102).

Are there plans to implement a Sidekiq integration on OpenTelemetry?

**Comment by elskwid** [comment]
Hi @danielmbarlow!

Yes, we absolutely have plans to implement a Sidekiq integration (we're calling them adapters for now 😄). These are part of #67 for now. We've started with some simple adapters: Faraday in #148 and Sinatra in #149. The goal is to come up with a blueprint for how to write adapters for this library. We'd love your feedback, ideas, and contributions.

Are you interested in working on the Sidekiq adapter given that you've worked on the same for Opencensus?

**Comment by danielmbarlow** [comment]
> We've started with some simple adapters
I'll watch those PRs to see the kind of approach you're taking, thanks.

> Are you interested in working on the Sidekiq adapter 
Quite likely. I'll have to get approval from my project manager first, though. Will be in touch.

**Comment by danielmbarlow** [comment]
I haven't been given approval to work on this so far. We put a lot of time into developing the OpenCensus sidekiq integration, and I don't think I'll get a green light any time soon to work on it's replacement.

**Comment by fbogsany** [comment]
I'll take a look at the OpenCensus Sidekiq integration. We will probably start work on this next week.

**Comment by fbogsany** [comment]
@robertlaurin can you please comment on this issue so I can assign it to you?

**Comment by robertlaurin** [comment]
> 
> 
> @robertlaurin can you please comment on this issue so I can assign it to you?

👋

**Comment by mwear** [comment]
I'm closing this because we have sidekiq instrumentation from #212. If we need any improvements or changes, we can track those separately.
