### ISSUE TITLE
OTLP Exporter for Logs

### ISSUE THREAD

**Issue by kaylareopelle** [open-telemetry/opentelemetry-ruby#1525]
Our current OTLP exporter is set up to exclusively send traces. This issue will either adapt current exporters or create a new, temporary exporter to send logs over OTLP. Support for HTTP will likely come first, followed by gRPC.

**Comment by travisbell** [comment]
Hey @kaylareopelle, do you know where this project is at? Just curious when we might get to use a more generalized logging exporter. Thanks.

**Comment by kaylareopelle** [comment]
Hi @travisbell thanks for checking in! Apologies about the delay here. 

There is an unreviewed OTLP logs exporter, along with other code to make Ruby spec-compliant for the Logs signal, available in this PR on my fork: https://github.com/kaylareopelle/opentelemetry-ruby/pull/6 

The current process is to release small parts of this code to the main opentelemetry-ruby repository for review, and then revise the WIP branch as needed. I don't have a good sense of when all those code will be merged into `main`.

If you'd like to test out the WIP logs implementation, you can follow the instructions in this gist: https://gist.github.com/kaylareopelle/76079747c1a7528449670b8bd1c78893 

I also have a demo repository that integrates OpenTelemetry logs into a small Rails application: https://github.com/kaylareopelle/otel_ruby_logs_demo

I'm updating the branches about once a week to stay in sync with the latest changes upstream.

If you decide to give this experimental code a try, please let me know how it goes. You can comment here, open an issue on the demo repo, or add a comment to the gist.

**Comment by kaylareopelle** [comment]
WIP, unreviewed code for this issue, along with other parts of the logs SDK, can be found in https://github.com/kaylareopelle/opentelemetry-ruby/pull/6

**Comment by cidemaxio** [comment]
What progress has been made and what else remains to be done?  We would like to use this for logging from our ruby code.

**Comment by kaylareopelle** [comment]
Hi @cidemaxio! Thanks for reaching out. It's great to hear you'd like to use OTel Ruby logs. 

Here's the project board for [the Logs signal](https://github.com/orgs/open-telemetry/projects/99) that tracks what remains to be done. I have [a draft PR for the OTLP exporter on my fork](https://github.com/kaylareopelle/opentelemetry-ruby/pull/12) with a todo list in the description for work to do before opening the PR in the main repo. 

There is at least one other PR that needs to be opened for the SDK/API regarding configuration and instrument registries. After both that PR and https://github.com/open-telemetry/opentelemetry-ruby/pull/1696 are merged, we should be ready to release the logs SDK, API and OTLP exporter gems.

**Comment by kaylareopelle** [comment]
Hi, @cidemaxio! PR is now opened for the OTLP Log Record Exporter: #1727 

Please take a look if you're interested! Additional feedback from the community may help speed up the process to merge/release the gem.

The other PR related to the SDK/API I mentioned in my last comment has been opened too: #1725

**Comment by cidemaxio** [comment]
Thanks for the update @kaylareopelle!  We will look at that PR.

**Comment by wsmoak** [comment]
@kaylareopelle both PRs seem to have conflicts.  Could you bring them up to date with main if you have a chance?

**Comment by kaylareopelle** [comment]
Thank you, @wsmoak! The merge conflicts have been resolved 😄

**Comment by kaylareopelle** [comment]
This is fantastic news. Thanks for testing, @wsmoak! 

Where did you find the docker run command? I'm wondering if there's a place we could update the documentation to include your port finding.

It's a bit off-topic for this issue, but if you're interested in trialing a Ruby Logger bridge to automatically emit your Rails logs as OpenTelemetry Logs, you can pull in the branch on this PR: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/983 

This is intended for the standard Ruby Logger class. If you're using semantic logger, there's a prototype here: https://github.com/reidmorrison/semantic_logger/pull/292

**Comment by wsmoak** [comment]
The docker run command I mentioned is the one in the otel collector quickstart:   https://opentelemetry.io/docs/collector/quick-start/ -> step 3

I had that running, but when I started the Rails app, it complained that it couldn't export logs. Could this error have more details about where it was trying to send them?
`E, [2024-10-17T18:47:03.126824 #86414] ERROR -- : OpenTelemetry error: Unable to export 3 log records`

 I eventually sorted out that the Ruby SDK was speaking HTTP and I nothing was listening on 4318 in the collector.

(And I did see it wrapping the Rails logs already, I think I picked up the contrib gem from your [otel_ruby_logs_demo](https://github.com/kaylareopelle/otel_ruby_logs_demo) Rails example.) Thanks!

**Comment by kaylareopelle** [comment]
Hi @wsmoak, I updated the OTLP log exporter to log an OpenTelemetry error with more detail whenever it returns a FAILURE status code. Could you give it a try and let me know if that information would have helped debug the connection problem you encountered? 

Here's the commit that introduced the logging: abfcd5466902b1eb21b4a3b4e8519fec10d5f0ab

**Comment by kaylareopelle** [comment]
Hi @marcelaraujo! Thank you for the reminder! I'm in the process of updating the branch with the latest changes. There are a few discrepancies I want to take a closer look on and a few more tests I want to run. I'm not certain if the latest push works. I'll add a comment here when it's ready to go.

**Comment by marcelaraujo** [comment]
Hi @kaylareopelle again,

I pulled your demo repo, installed the deps and tried to run the Rails

```
 /usr/local/bundle/bundler/gems/opentelemetry-ruby-contrib-d00bc1da07fe/instrumentation/logger/lib/opentelemetry/instrumentation/logger/instrumentation.rb:22:in `<class:Instrumentation>': uninitialized constant OpenTelemetry::Instrumentation::Logger::VERSION (NameError)

        option :version, default: OpenTelemetry::Instrumentation::Logger::VERSION, validate: :string
```

**Comment by kaylareopelle** [comment]
Hi @marcelaraujo! The branch is updated and ready for use. 🚀

**Comment by marcelaraujo** [comment]
The folder `exporter/otlp-logs/*.gemspec` is missing.

**Comment by kaylareopelle** [comment]
Hi @marcelaraujo. My apologies, I should've mentioned this in my earlier comment.

To use experimental logs, we no longer need to install `opentelemetry-exporter-otlp` from the branch source. I had a few problems with versioning when I initially copied the OTLP traces exporter to build the OTLP logs exporter. 

If you'd like to export traces, I recommend installing the latest version of `opentelemetry-exporter-otlp` from RubyGems. Do   not install it from my fork.

```diff 
# OTLP Exporters with logging enhancements
+ gem 'opentelemetry-exporter-otlp'
- gem 'opentelemetry-exporter-otlp',
-   git: 'https://github.com/kaylareopelle/opentelemetry-ruby',
-   branch: 'log-record-processor3',
-   glob: 'exporter/otlp/*.gemspec'
``` 

I'll update my gist to stop installing `opentelemetry-exporter-otlp` from my fork.

If you install the gem from source and still run into this problem, let me know. Something else may be going on.

**Comment by kaylareopelle** [comment]
@marcelaraujo - Something else was going on with the OTLP exporter. 🤦 

The namespaces for the OTLP exporter for traces and the OTLP exporter for logs collided because they both had the same constant. I've updated the OTLP log exporter now to have its own unique namespace: `OpenTelemetry::Exporter::OTLP::Logs`. This follows the pattern we implemented for metrics. You can find the full discussion [here](url).

This fix is now part of the `log-record-processor3` branch on my fork.
