### ISSUE TITLE
Testing: Adapters should work with multiple versions of libraries

### ISSUE THREAD

**Issue by duonoid** [open-telemetry/opentelemetry-ruby#155]
Split from https://github.com/open-telemetry/opentelemetry-ruby/pull/148#pullrequestreview-315262385 -- the instrumentation adapter (faraday specifically, all generally) should work with multiple versions of the libraries they are instrumenting.

Consider integrating 'appraisals' gem.

**Comment by duonoid** [comment]
I have started on this.

**Comment by elskwid** [comment]
@duonoid I've assigned it to you. Have fun 💃

**Comment by mwear** [comment]
In case it's useful, it appears the testing for contrib is spread across the two directories, spec and test, in dd-trace-rb.

* https://github.com/DataDog/dd-trace-rb/tree/master/spec/ddtrace/contrib
* https://github.com/DataDog/dd-trace-rb/tree/master/test/contrib

**Comment by duonoid** [comment]
I think this issue is able to be closed, since there is some ongoing testing guidance mentioned in #168.

**Comment by mwear** [comment]
👍
