### ISSUE TITLE
Resource should support the same attribute types as span attributes

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#158]
I think this is just a documentation change in [Resource](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/lib/opentelemetry/sdk/resources/resource.rb) to match [Span#set_attribute](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/api/lib/opentelemetry/trace/span.rb).

Addresses https://github.com/open-telemetry/opentelemetry-specification/pull/356

**Comment by fhwang** [comment]
@fbogsany I can look into this.
