### ISSUE TITLE
Instrumentation Repository

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#159]
Currently instrumentation is cohabiting the same repo along with the API and SDK. It's convenient to have both in the same repo as we are rapidly iterating on the API and SDK, but do we want the instrumentation to be there longer term?

A [repo](https://github.com/open-telemetry/opentelemetry-auto-instr-ruby) has been created for this purpose, it can remain empty, or be deleted if we decide we don't need it.

If we would like to have this repo now, or reserved for future use, we should appoint some maintainers. There is an issue about this: https://github.com/open-telemetry/community/issues/275. I'm guessing we would like the same maintainers as we have here.

If anyone has thoughts about this, feel free to post as comments here. We can also discuss this at the next SIG meeting.

**Comment by fbogsany** [comment]
My opinion:
- continue to use the same repo for now, until we understand the shape of the instrumentation better
- move the instrumentation to the other repo once we have some well understood instrumentation patterns (including configuration)
- appoint the same set of maintainers for the other repo as we have here

Rationale for eventually moving the instrumentation is that the API and SDK will typically move in lockstep, but the instrumentation will typically support a range of versions of the API, and be more loosely coupled.

**Comment by johnnyshields** [comment]
@fbogsany can this issue be closed? It seems the pattern the team has is working for now.
