### ISSUE TITLE
Adding backtraces to error logs

### ISSUE THREAD

**Issue by gabriel1402** [open-telemetry/opentelemetry-ruby#1591]
Hello!

First, thanks for all the hard work done in this library. Some time ago, we were experiencing an error within our app. The error was correctly logged, however, it was a bit cryptic itself, and it helped shed some light when we monkey-patched this method from the library, by adding the backtrace:

https://github.com/open-telemetry/opentelemetry-ruby/blob/c7ef4085cb020d62725da1f3dc29f169dd1db267/api/lib/opentelemetry.rb#L36-L38

This is how we monkey-patched it:

```ruby
module OpenTelemetryExtensions
  module OpenTelemetry
    def error_handler
      @error_handler = ->(exception: nil, message: nil) { logger.error("OpenTelemetry error: #{[message, exception&.message, exception&.backtrace&.join("\n")].compact.join(' - ')}") }
    end
  end
end
```

Was this originally conceived by design, or could this be an addition that might be useful for other developers?

**Comment by arielvalentin** [comment]
You should be able to override the error handler without monkey patching:

https://github.com/open-telemetry/opentelemetry-ruby/blob/c7ef4085cb020d62725da1f3dc29f169dd1db267/api/lib/opentelemetry.rb#L27


You can see an examples of how we do it as part of initialization for our test helpers:

https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-ruby-contrib%20error_handler&type=code
