### ISSUE TITLE
Add support for array-valued attributes

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#160]
See https://github.com/open-telemetry/opentelemetry-specification/pull/368

**Comment by fhwang** [comment]
As long as I'm looking at this: There seem to be a number of places where the type of `attributes` is not being validated, for example https://github.com/open-telemetry/opentelemetry-ruby/blob/master/api/lib/opentelemetry/trace/event.rb#L39

Should I add validation in these places, raising `ArgumentError` in cases where `attributes` is invalid?

**Comment by mwear** [comment]
Having the observability system raise runtime exceptions is frowned upon see: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md. The preferred approach is to use defaults or discard data that doesn't conform and log a message about it.

**Comment by mwear** [comment]
Another trend you may notice, is that validating data can sometimes be expensive to do up front, and since data is sampled, it often is more efficient to validate, drop or correct data on export.
