### ISSUE TITLE
How to set the traces data limit?

### ISSUE THREAD

**Issue by k1r8r0wn** [open-telemetry/opentelemetry-ruby#1615]
Hello! It's not a bug, actually, but maybe the request for new functionality...

The custom Grafana Tempo settings has limit for 5Mb (default 50 from the [article (see the Use exporters section)](https://grafana.com/blog/2023/12/18/opentelemetry-best-practices-a-users-guide-to-getting-started-with-opentelemetry/)) and doesn't receive traces which are over it.

<img width="724" alt="Снимок экрана 2024-03-14 в 15 20 59" src="https://github.com/open-telemetry/opentelemetry-ruby/assets/8123661/bef8231c-5af8-46b5-b7f4-5df53a51cfb0">

How to set the limits of sended traces inside the OTEL? (gzip compression is enabled by default).

Any ideas appreciated!

**Stack gems used**

```rb
  gem "opentelemetry-exporter-otlp"
  gem "opentelemetry-instrumentation-graphql"
  gem "opentelemetry-instrumentation-pg"
  gem "opentelemetry-instrumentation-que"
  gem "opentelemetry-instrumentation-rack"
  gem "opentelemetry-sdk"
end

**Comment by arielvalentin** [comment]
You may adjust batch sizes using as well as other values such as attribute limits using standard SDK environment variables, e.g.

https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#batch-span-processor

**Comment by k1r8r0wn** [comment]
> You may adjust batch sizes using as well as other values such as attribute limits using standard SDK environment variables, e.g.
> 
> https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#batch-span-processor

Much appreciated, @arielvalentin, will try.
