### ISSUE TITLE
New Meeting Time

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#178]
As discussed at the last SIG meeting, it would be nice if we could move the day and time of the current meeting to allow for participation in the JS SIG which currently meets during the same time slot. There weren't any objects during the SIG meeting and it looked like 9 AM PST (UTC -8) on either Tuesday or Thursday would work for folks. I created a Doodle so people can vote for a time that works. You can choose multiple times if they work and there's also a column to indicate that neither of the times work. If the suggested times do not work for people, we can try to find other options. 

https://doodle.com/poll/a988qu5kgnctu3ym

cc'ing the regular SIG attendees: @benedictfischer09 @dazuma @duonoid @elskwid @fbogsany

**Comment by mwear** [comment]
Everyone @ mentioned has voted. Thursdays at 9 AM PST works for everyone, so that will be our new meeting time. I'll see how I can get it moved officially on the OpenTelemetry calendar.

**Comment by fbogsany** [comment]
> I'll see how I can get it moved officially on the OpenTelemetry calendar.

I've done that previously. I'll see if I can do it again.

**Comment by fbogsany** [comment]
I've moved the meeting and changed the Zoom link to https://zoom.us/j/8287234601.

IIRC we have 3 Zoom rooms for OpenTelemetry.

The Python SIG is immediately before our meeting and the Go SIG is immediately after our meeting, both using https://zoom.us/j/6729396170.

The Java auto-instrumentation SIG meets every 2nd Thursday in our timeslot using https://zoom.us/j/8203130519.

Every 2 months, the OpenTelemetry Community & Governance Office Hours are held immediately after our meeting using the same Zoom room as us, so we can expect very occasional expulsions.

**Comment by mwear** [comment]
Thanks @fbogsany!

**Comment by mwear** [comment]
Closing since the meeting time has officially been changed.
