### ISSUE TITLE
Spans and Errors

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#181]
### Background

As we convert instrumentation, ensuring that we preserve error recording from the original instrumentation is becoming a problem. One of the big bottlenecks to this problem is that there is not clear guidance on how to record errors in OpenTelemetry. Several proposals have surfaced recently, notably: 

* https://github.com/open-telemetry/opentelemetry-specification/pull/427
* https://github.com/open-telemetry/opentelemetry-specification/pull/432

I wrote some Ruby code to see how handling an error would look for each of the proposals. It's in this [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/427#issuecomment-584424963), but I'll cut and paste it for reference:

Example for #427 

```ruby
begin
  buggy_method     # raises an exception when called
rescue => e
  span.add_event(name: 'error',
                 attributes: {
                   'error.type' => e.class,
                   'error.message' => e.message,
                   'error.stack' => e.backtrace
                 })
end
```

Example for #432

```ruby
begin
  buggy_method     # raises an exception when called
rescue => e
  span.add_event(name: 'error',
                 attributes: {
                   'log.type' => e.class,
                   'log.severity' => 'error',
                   'log.message' => e.message,
                   'frame.file' => e.backtrace_locations[0].absolute_path,
                   'frame.line' => e.backtrace_locations[0].lineno,
                   'frame.func' => e.backtrace_locations[0].label,
                   'frame.stack' => stack_to_json(e)
                 })
end

def stack_to_json(e)
  JSON.dump(
    e.backtrace_locations.map do |loc|
      { 'frame.file' => loc.absolute_path, 'frame.line' => loc.lineno, 'frame.func' => loc.label }
    end
  )
end
```

### Should we add a Span#add_error or Span#record_error convenience method?

In writing that example, one thing became clear to me - we're going to want a convenience method to simplify recording errors.

The Go SIG has reached the same conclusion:

* https://github.com/open-telemetry/opentelemetry-go/issues/248
* https://github.com/open-telemetry/opentelemetry-go/pull/473

I'm wondering if we should preemptively add a convenience method. It could even no-op for the time being, or perhaps speculatively record an event with semantic conventions we expect to change. Possible names could be:

* Span#add_error
* Span#record_error

### Should in_span record and reraise exceptions?

If we decide to add a convenience method for recording an error, does it make sense for Tracer#in_span to automatically rescue, record, and reraise exceptions. Currently dd-trace does this, and to replicate that behavior with `in_span` error handling needs to be inlined.

**Comment by fbogsany** [comment]
I think we can close this @mwear.
