### ISSUE TITLE
Improve Redis instrumentation

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#197]
The Redis instrumentation, which is a port of the dd-trace version, instruments redis by patching the `call` and `call_pipeline` methods. We might be missing some calls by not also patching `call_loop` and `call_pipelined`. We should look into adding coverage for the additional methods.

See: https://github.com/open-telemetry/opentelemetry-ruby/pull/176#pullrequestreview-361604975

**Comment by fbogsany** [comment]
Is this required for the RC milestone @mwear?

**Comment by mwear** [comment]
It's not. I believe these were suggestions that I captured based on the Shopify version of the Redis instrumentation. If we are not missing anything by not instrumenting the methods discussed above, we can consider closing this.

**Comment by fbogsany** [comment]
I'm going to keep this open, but remove the milestone.

**Comment by fhwang** [comment]
I can give this a try 🙋

**Comment by fbogsany** [comment]
Thanks @fhwang ! I've assigned it to you.

**Comment by fhwang** [comment]
@mwear Regarding `call_loop`: This is primarily used for pubsub subscribers. Is it settled that we want to treat these messages as a new span in the same trace of the publisher? And if so, is there guidance in the spec about how to propagate context over Redis messages?

**Comment by mwear** [comment]
I opened this issue to capture some feedback from @fbogsany based on Shopify's internal instrumentation, so I will defer to  him on specifics. I think making sure that we are spans for all Redis operations would be a good first step. I don't know that there any guidance on context propagation over Redis, but it's an interesting idea. I took a quick look at JS Redis instrumentation, and it doesn't handle it.

**Comment by fbogsany** [comment]
Shopify doesn't use Redis pubsub, so I can't offer any insights there. Perhaps we can just instrument `call_pipelined` for now?

**Comment by fhwang** [comment]
What's the general principle regarding what level of method calls we're hooking into? `call_pipelined` is actually called by `call_pipeline`, so if we instrument both we'll be getting a lot of double spans.

I'm not sure either of these methods count as the public interface of this library -- they aren't documented, they aren't directly tested. Should we simply instrument every call to every public method on the main Redis class that results in an immediate call to the redis-server?

**Comment by fbogsany** [comment]
It varies. In general, the goal should be to instrument as close to the wire as possible. Many gems either don't provide instrumentation hooks or provide hooks that are inappropriate for tracing. For example, the Redis gem provides a logger hook. but the logs are unstructured (we'd have to parse them to populate spans, and that'd be more brittle than the monkey-patching we do).

`call_pipelined` is also called [from outside the `call_pipeline` context](https://github.com/redis/redis-rb/blob/6542934f01b9c390ee450bd372209a04bc3a239b/lib/redis.rb#L134), which is why I suggested we instrument it.

I don't recall the rationale for the current form of the Redis instrumentation. At Shopify, we instrumented [`Client#process`](https://github.com/redis/redis-rb/blob/6542934f01b9c390ee450bd372209a04bc3a239b/lib/redis/client.rb#L241-L256) instead, which is a bottleneck for (almost?) all communication with the Redis server.

**Comment by fhwang** [comment]
Looks like the current instrumentation was inspired by `dd-trace-rb`. I'm not sure what's the best way to get context on their decision-making.

Naively, I wonder if it would make more sense to convert this instrumentation to instrument calls to `Client#process` and `Client#read` instead. From a quick reading of the library, it looks like that would capture all Redis commands.

**Comment by fbogsany** [comment]
> Naively, I wonder if it would make more sense to convert this instrumentation to instrument calls to `Client#process` and `Client#read` instead. From a quick reading of the library, it looks like that would capture all Redis commands.

That sounds like a good thing to try. I'd be very much in favour of that.

**Comment by robbkidd** [comment]
For what it's worth, patching `Client#process` is [the means by which Honeycomb instrumented Redis](https://github.com/honeycombio/beeline-ruby/blob/4dd9761902bffc7bd7b0210a27fb029a7ac4223c/lib/honeycomb/integrations/redis.rb#L34-L42).

**Comment by fhwang** [comment]
Sounds good. One wrinkle I just thought of: How do we want to handle pipelined calls? One span per pipeline request? Or multiple spans, one per Redis command within the single pipeline request?

**Comment by ajvondrak** [comment]
FWIW, the Honeycomb implementation just joins together the pipelined commands into a single `redis.command` string: https://github.com/honeycombio/beeline-ruby/blob/4dd9761902bffc7bd7b0210a27fb029a7ac4223c/lib/honeycomb/integrations/redis.rb#L137 Conceptually, I think this makes sense: 1 API request = 1 span, just that the request happens to contain multiple commands & return a bulk reply.

**Comment by ajvondrak** [comment]
If you did have one span per redis command, you'd probably want to introduce some sort of parent `pipeline` span that tied them all together. Otherwise, it'd be impossible to distinguish between commands that were fired serially vs in a pipeline when looking at the trace.

**Comment by fbogsany** [comment]
Shopify also has a single span for the pipelined commands - very similar to what Honeycomb has. The reason this makes sense is that it represents a single “unit of work” and it isn’t possible to discover the timing of the individual commands in the pipeline.
