### ISSUE TITLE
HTTP status codes and errors

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#198]
Currently our HTTP instrumentation will record errors for unhandled exceptions. Should we create errors based on response codes? If so, we should do this uniformly across our instrumentation adapters. We may also want to add this to the datadog porting guide as well.

**Comment by fbogsany** [comment]
We appear to be setting status based on HTTP response codes in all of our HTTP client and server framework auto-instrumentation. Is anything else required for this issue @mwear?

**Comment by mwear** [comment]
I think we are doing the right thing. Closing...
