### ISSUE TITLE
Enable CI integration

### ISSUE THREAD

**Issue by indrekj** [open-telemetry/opentelemetry-ruby#20]
PRs should be checked with a CI tool (e.g. travis, circleci, etc) to avoid pushing breaking changes to master. The api has `bundle exec rake` command to run tests and rubocop.

**Comment by mwear** [comment]
Does anyone have a preference for which CI tool we should use?

**Comment by fbogsany** [comment]
Java, Python, Protobuf and Service projects are all on TravisCI: https://travis-ci.org/open-telemetry
