### ISSUE TITLE
Propagation updates

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#204]
The spec has diverged from OTEP-66 in a couple of ways. The OTEP had propagators divided into injectors and extractors and had a global propagation object where http_injectors and http_extractors could be configured. It also had `inject` and `extract` methods that could accept an arbitrary list of propagators (or in fallback to the globals). See: https://github.com/open-telemetry/oteps/blob/master/text/0066-separate-context-propagation.md#propagation-api

The spec has changed this so that there is a composite propagator option and a single global propagator. See: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md#composite-propagator

The separation of injectors and extractors helped handling keys that have been Rack normalized. I could see us suggesting that the spec be relaxed to allow composite injectors and extractors, and corresponding globals. 

I thought this was discussion worthy before moving in either direction.

**Comment by fbogsany** [comment]
I think this is done with #214 and #215 ?

**Comment by mwear** [comment]
'tis
