### ISSUE TITLE
Spec vs implementation difference for context extraction

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#233]
The [specification for trace context extraction](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md#extract) states:

> If a value can not be parsed from the carrier for a cross-cutting concern, the implementation MUST NOT throw an exception. It MUST store a value in the `Context` that the implementation can recognize as a null or empty value.

Our implementation does not do this. Specifically, we do *NOT* modify the `Context` if we can't parse a value from the carrier.

Propagator:
https://github.com/open-telemetry/opentelemetry-ruby/blob/79b047a38d43782bf0733c7338a5c00aec92c278/api/lib/opentelemetry/context/propagation/propagator.rb#L56

Noop extractor:
https://github.com/open-telemetry/opentelemetry-ruby/blob/79b047a38d43782bf0733c7338a5c00aec92c278/api/lib/opentelemetry/context/propagation/noop_extractor.rb#L20-L22

Composite propagator:
https://github.com/open-telemetry/opentelemetry-ruby/blob/79b047a38d43782bf0733c7338a5c00aec92c278/api/lib/opentelemetry/context/propagation/composite_propagator.rb#L62-L69

Text extractor:
https://github.com/open-telemetry/opentelemetry-ruby/blob/79b047a38d43782bf0733c7338a5c00aec92c278/api/lib/opentelemetry/trace/propagation/trace_context/text_extractor.rb#L38-L53

It isn't clear whether what we're doing is more appropriate and we should change the spec, or if we need to conform to the spec (and have some representation of "I couldn't extract anything").

A key concern is that if someone has existing context and then calls `extract`, subsequent spans should use the "invalid" (failed-to-extract) context as the parent, not the previously existing context.

**Comment by fbogsany** [comment]
@mwear is there a spec issue or OTEP relevant to this? I think you mentioned on the last SIG call that you thought the spec would be changed to something closer to what we have.

**Comment by mwear** [comment]
This is no longer needed due to: https://github.com/open-telemetry/opentelemetry-specification/pull/671
