### ISSUE TITLE
Add documentation for Net::HTTP

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#238]
Add documentation for the Net::HTTP instrumentation adapter. The implementation exists [here](https://github.com/open-telemetry/opentelemetry-ruby/tree/master/adapters/net_http), but we should have a readme describing its behavior and options.

**Comment by shovnik** [comment]
Hi, is this still available? I'd love to handle this. The link seems to be broken by the way. - cc @alolita
