### ISSUE TITLE
Add documentation for Redis

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#240]
Add documentation for the Redis instrumentation adapter. The implementation exists [here](https://github.com/open-telemetry/opentelemetry-ruby/tree/master/adapters/redis), but we should have a readme describing its behavior and options.

**Comment by amanbrar1999** [comment]
Hi! is this issue free to pick up? I'd like to work on it - cc @alolita

**Comment by amanbrar1999** [comment]
PR has been merged so I believe this should be good to close @fbogsany
