### ISSUE TITLE
Add documentation for Sidekiq

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#241]
Add documentation for the Sidekiq instrumentation adapter. The implementation exists [here](https://github.com/open-telemetry/opentelemetry-ruby/tree/master/adapters/sidekiq), but we should have a readme describing its behavior and options.

**Comment by AzfaarQureshi** [comment]
Hi! Am I free to pick this up? The link (https://github.com/open-telemetry/opentelemetry-ruby/tree/master/adapters/sidekiq) seems to be broken though, did the implementation get refactored somewhere else?

**Comment by ericmustin** [comment]
@AzfaarQureshi sounds good, I've assigned to you. the repo structure changed slightly since this issue was filed, it can be found here now https://github.com/open-telemetry/opentelemetry-ruby/tree/master/instrumentation/sidekiq
