### ISSUE TITLE
dalli instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#244]
Convert Datadog instrumentation for dalli to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md	)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/dalli)

**Comment by sribalakumar** [comment]
@fbogsany @mwear 

We have done the [Dalli porting](https://github.com/RashmiRam/opentelemetry-ruby/tree/v0.4.0-ruby-2.4-compatible/adapters/dalli ) and Iam interested in contributing this enhancement as PR.

Let me know if the work is already started by someone else ?

**Comment by fbogsany** [comment]
@sribalakumar can you please coordinate with @robertlaurin? He has implemented this as well & we planned to contribute it this week. I think it would be useful to get both implementations up as PRs that we can review together, and cherry-pick the best of both.

**Comment by robertlaurin** [comment]
I've put up a draft PR porting the internal shopify implementation here https://github.com/open-telemetry/opentelemetry-ruby/pull/355

**Comment by sribalakumar** [comment]
@fbogsany @robertlaurin Thanks, I'll be able to send the alternate PR (we are patching at `Server.request` level, as in Datadog) over this weekend.

**Comment by sribalakumar** [comment]
@robertlaurin @fbogsany I had a chance to go through https://github.com/open-telemetry/opentelemetry-ruby/pull/355 and its pretty much the [same definitions](https://github.com/RashmiRam/opentelemetry-ruby/tree/v0.4.0-ruby-2.4-compatible/adapters/dalli) that we have also back ported from Datadog. 

So to avoid duplicate efforts I have started with https://github.com/open-telemetry/opentelemetry-ruby/pull/363
