### ISSUE TITLE
GraphQL instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#246]
Convert Datadog instrumentation for GraphQL to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/graphql)

**Comment by robertlaurin** [comment]
Added in https://github.com/open-telemetry/opentelemetry-ruby/pull/527
