### ISSUE TITLE
DelayedJob instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#251]
Convert Datadog instrumentation for DelayedJob to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/delayed_job)

**Comment by johnnyshields** [comment]
I'm working on this.

**Comment by johnnyshields** [comment]
Raised PR: https://github.com/open-telemetry/opentelemetry-ruby/pull/446
