### ISSUE TITLE
ActiveModelSerializers instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#258]
Convert Datadog instrumentation for ActiveModelSerializers to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/active_model_serializers)

**Comment by johnnyshields** [comment]
I did this in PR #477. Please close this issue.
