### ISSUE TITLE
API: consider adding an empty Resource

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#27]
The [Resource spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-resources.md#the-empty-resource) states:

> It is recommended, but not required, to provide a way to quickly create an empty resource.

Should we add a `Resource::EMPTY` constant? As with #25 it isn't clear if this has value, if `Resource` is only attached to a `Tracer`, and `SpanData` is removed.

**Comment by mwear** [comment]
If it has value, we should add it, otherwise we can save on memory overhead by omitting it.

**Comment by fbogsany** [comment]
It's probably going to be useful. https://github.com/open-telemetry/rfcs/pull/8 adds an optional resource parameter to span creation.

**Comment by fbogsany** [comment]
From the discussion on today's SIG call, I'm now leaning toward YAGNI. This part of the spec is still in flux, and it isn't clear that an empty Resource is useful.

Any objections to closing this issue?

**Comment by fbogsany** [comment]
Resources are moved from the API to the SDK as part of the OTEP to [remove out-of-band reporting](https://github.com/open-telemetry/oteps/blob/master/text/0007-no-out-of-band-reporting.md#resource-changes). So YAGNI.
