### ISSUE TITLE
Extract Rack adapter into dependent gem

### ISSUE THREAD

**Issue by martinisoft** [open-telemetry/opentelemetry-ruby#271]
Since each adapter is it's own gem it would be helpful to standardize and re-use adapters like Rack, which is a common dependency between web based gems like Sinatra (and by extension Padrino which is based on Sinatra) and Rails. If there is desire to support [Hanami](https://hanamirb.org/) in the future, this would be an easy first step to include the Rack gem as a dependency. Here is a rough list of tasks to complete this (I think):

- [ ] Merge all of the separate Rack implementations back into the rack adapter gem
- [ ] Make the rack adapter a dependency for the Sinatra gem
- [ ] Stub out a very barebones Rails adapter by simply implementing the Rack gem as a dependency
- [ ] Stub out a very barebones Hanami adapter by simply implementing the Rack gem as a dependency

**Comment by genebean** [comment]
> Merge all of the separate Rack implementations back into the rack adapter gem
Can you elaborate on this part? I think I could help with it a little but want to make sure I understand the ask

**Comment by fbogsany** [comment]
> > Merge all of the separate Rack implementations back into the rack adapter gem
> 
> Can you elaborate on this part? I think I could help with it a little but want to make sure I understand the ask

I think this may be a reference to https://github.com/open-telemetry/opentelemetry-ruby/pull/225, in particular the registration of the Rack middleware in the Railtie and the definition of a Rails-specific middleware. I don't have more context than that, unfortunately.

**Comment by fhwang** [comment]
I believe we can close this issue, right? Looks like there are now very few references to Rack in instrumentations other than the Rack instrumentation.
