### ISSUE TITLE
Support for older versions of ruby

### ISSUE THREAD

**Issue by RashmiRam** [open-telemetry/opentelemetry-ruby#281]
All opentelemetry gems support ruby version >= 2.4. Rails 5 itself requires minimum of Ruby 2.2 and I guess majority of major ruby applications are in Rails 5 or even below.  
So, Would it be a reasonable ask to support for ruby >= 2.2?

**Comment by fbogsany** [comment]
In #10 we decided to only support Ruby versions that are supported by the ruby-core team, namely `normal maintenance` and `security maintenance` levels. Based on this, we removed support for Ruby 2.4 in #226. 

We need to draw a line somewhere. Supporting very old versions of Ruby limits our ability to leverage new language and library features, and is cumbersome to maintain. Given the small pool of maintainers, I don’t see us changing this policy. Others may have different opinions.

**Comment by RashmiRam** [comment]
Thanks for the explanation @fbogsany. I understand that maintenance would be tedious. But, I suppose lots of rails apps using older versions of ruby will find it difficult to move to Opentelemetry Ruby especially if they are using an existing Opentracing Implementation gems. They seem to support ruby >= 2.2 or 2.3. Just my 2 cents.

**Comment by johnnyshields** [comment]
@fbogsany can this issue be closed? It seems reasonable for OTEL to skip support for EOL versions of Ruby. (Ruby 2.4 was EOL as of March 31, 2020)

**Comment by duaneking** [comment]
> In #10 we decided to only support Ruby versions that are supported by the ruby-core team, namely `normal maintenance` and `security maintenance` levels. Based on this, we removed support for Ruby 2.4 in #226.
> 
> We need to draw a line somewhere. Supporting very old versions of Ruby limits our ability to leverage new language and library features, and is cumbersome to maintain. Given the small pool of maintainers, I don’t see us changing this policy. Others may have different opinions.

As respectfully as I can say, this is a bad idea as there are many projects that desperately need this kind of thing in order to assure the best migration path forward.
