### ISSUE TITLE
Introduce a changelog

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#290]

**Comment by mwear** [comment]
@dazuma suggested adopting [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in #138. I don't think our commit messages follow the required conventions at this time. If this looks interesting to folks, we can see what it would take to migrate.

**Comment by fbogsany** [comment]
🤷 it doesn’t look like (m)any of the other language SIGs are using conventional commits. I’m not averse to trying it out, but we’ll have to bikeshed tooling, etc. I’d probably lean toward a manually maintained changelog to start with.

**Comment by ericmustin** [comment]
I'll grab this one

**Comment by fbogsany** [comment]
Fixed in #294
