### ISSUE TITLE
ProbabilitySampler.sample_trace_id? should account for spec compliant trace_id

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-ruby#298]
I believe that https://github.com/open-telemetry/opentelemetry-ruby/pull/280 introduced an edge case bug in the `sample_trace_id?` private method on `ProbabilitySampler`
https://github.com/open-telemetry/opentelemetry-ruby/blob/a76c4285729caee021fb5557b21f696f62ba4c6d/sdk/lib/opentelemetry/sdk/trace/samplers/probability_sampler.rb#L58

Where, for a `ProbabilitySampler` with sampling rate < 1.0, the `sample_trace_id?` method will always return `true`. I believe this is because the trace_id is not in the expected format for the comparison to work as intended, and the LOC needs to be updated something like:

`@probability == 1.0 || trace_id.unpack1('H*')[16, 16] < @id_upper_bound `

I may be mistaken but some testing locally seems to support this, just flagging this now (sorry to notice this only just after v0.5 release 😢 !)

**Comment by fbogsany** [comment]
Thanks very much for reporting this @ericmustin! I'll fix this ASAP (tonight or tomorrow). We'll need a 0.5.1 release of the SDK for this, unfortunately - sorry @mwear! 😞

**Comment by mwear** [comment]
Fix released in: https://rubygems.org/gems/opentelemetry-sdk/versions/0.5.1
