### ISSUE TITLE
Add instrumentation packages to the registry

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#304]
https://opentelemetry.io/get-involved/#registry

**Comment by ericmustin** [comment]
@mwear can you assign this to me? Should be able to get to this soon.

**Comment by genebean** [comment]
what all are you looking for with this - just adding entries for things like sinatra and such?

**Comment by fbogsany** [comment]
> what all are you looking for with this - just adding entries for things like sinatra and such?

Yep, exactly that.

**Comment by fhwang** [comment]
@ericmustin How would you feel about me taking this one? I was thinking of making some sort of Rake task to make it easier to automatically generate the Markdown files needed by the OTel registry.

**Comment by ericmustin** [comment]
ah my bad, dropped the ball here.  Yes i think a rake task would be appropriate, feel free to give it a shot. 
![ball drop](https://media.tenor.com/images/72967302d062f1a9f361bb181e589758/tenor.gif)

**Comment by fhwang** [comment]
Oops, I mis-linked these. #628 makes it *easier* to perform this task but it's still something to be run manually for now. I'll make that PR to `opentelemetry.io` now.
