### ISSUE TITLE
CI/CD: Generate CHANGELOGs automatically from Conventional Commit messages

### ISSUE THREAD

**Issue by dazuma** [open-telemetry/opentelemetry-ruby#306]
This is a proposal to:

* Adopt [Conventional Commit messages](https://conventionalcommits.org)
* Use the above to generate (a first pass of) changelogs automatically as part of the release process.

Specifically:

* All commit messages should conform to [Conventional Commits](https://conventionalcommits.org).
    * Three types of commit messages will appear as notes in the changelog:
        * Features that should normally trigger a semver-minor version release, should be labeled `feat:`.
        * Bug fixes that should normally trigger a semver-patch version release, should be labeled `fix:`.
        * Documentation updates that should normally trigger a semver-patch version release, should be labeled `docs:`.
    * Semver-major (breaking) changes should be notated as specified by [Conventional Commits](https://conventionalcommits.org).
    * Any other type of commit (e.g. `refactor:`, `tests:`, `chore:`) do not appear in the changelog.
* The release process will change to include automatic generation of changelog entries and automatic updating of the `VERSION` constant. Approximately, this will look like the following. (Bold items are human actions; non-bold are automated.)
    * **Someone will request a release by running a script (rake task or something), specifying which gem to release.**
    * The script will construct a commit as follows:
        * It will determine the last release version by searching for the last release tag for the gem
        * It will enumerate all commits since the last release tag
        * It will filter out any commits that do not touch the directory for the gem in question
        * It will create a changelog entry with lines based on the conventional commit messages for the remaining commits.
        * Based on the conventional commit messages, it will determine whether the release should be semver-major, minor, or patch, and update the `VERSION` constant accordingly.
    * The script will open a pull request with the above modification to the changelog and version. The pull request will be annotated somehow (perhaps a label) indicating that it is a release PR.
    * **A maintainer must approve and merge the PR (i.e. accept the release). The maintainer has the ability to tweak the changelog and/or version in the PR if needed.**
    * Once the PR is submitted, a GitHub Action will recognize it and initiate a release, doing the following:
        * It will wait for the commit checks (CI) to succeed. If they don't, it will emit an error notification and abort.
        * It will create the release tag
        * It will build and push the gem
        * It will build and push the docs (see #305)
        * It will emit a success notification.

**Comment by fbogsany** [comment]
> Semver-major (breaking) changes should be notated as specified by Conventional Commits.

The only thing to note here is that we don't want to bump the major version to 1 until we're ready to declare this GA, which is also dependent on the spec's GA. We *will* have breaking changes before then. Those should be flagged in the release notes, but should only result in a minor version bump for now.
