### ISSUE TITLE
Unable to add tags to spans

### ISSUE THREAD

**Issue by genebean** [open-telemetry/opentelemetry-ruby#312]
As best as I can tell from reading through things, there doesn't seem to be a way for me to add tags yet. My specific use case here is adding tags to an app instrumented via the `opentelemetry-ruby/instrumentation/sinatra/`.

**Comment by mwear** [comment]
:wave: @genebean. In OpenTelemetry tags are referred to as attributes. There is a [`Span#add_attribute`](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/lib/opentelemetry/sdk/trace/span.rb#L54-L79) method for adding them. If you are trying to get at a Span that has been created by auto-instrumentation, it might be available by calling [`Tracer#current_span`](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/api/lib/opentelemetry/trace/tracer.rb#L16-L22), although that will depend on what other work is being traced at the time.

Let us know if you still have questions.

**Comment by fbogsany** [comment]
The correct place to do this is with a `Resource`, like:
```ruby
OpenTelemetry::SDK.configure do |c|
  c.resource = OpenTelemetry::SDK::Resources::Resource.create({
    'service_name' => 'my-application-name',
    'service.version' => version,
  })
end
```

Unfortunately, we haven't yet implemented the mapping from OTel's `Resource` to Jaeger's `Process` yet: https://github.com/open-telemetry/opentelemetry-ruby/blob/7a10db9dea62b7cf109cd192f742a06a32554162/exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter.rb#L125-L133

#314 discusses how we might do this. We don't have consensus yet.
