### ISSUE TITLE
Disable tracing via context

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#313]
We should have a mechanism to disable tracing via a flag on the context. Other SIGs are considering similar approaches. See: https://github.com/open-telemetry/opentelemetry-js/issues/1040.

**Comment by johnnyshields** [comment]
This is probably needed for the Elasticsearch tracer. ES gem uses Faraday or Net::HTTP under the hood to talk to ES so we should probably disable that one, otherwise we get rather meaningless duplicate traces.
