### ISSUE TITLE
Export Resources from Jaeger exporter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#314]
The Jaeger exporter does not currently export Resources. It comes close to exporting them as process tags [here](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter.rb#L128-L130).

This is somewhat more complicated than it should be, because the specification allows for multiple tracer providers, where each can have different resources, but be hooked up to the same export pipeline. See [here](https://github.com/open-telemetry/opentelemetry-ruby/pull/277#discussion_r468218523) for more commentary. If we follow the spec, resources do not necessarily have a 1-1 relationship with processes, and that makes it difficult to add resource labels as Jaeger process tags.

We have two options (possibly more) that we can consider:
* We could ignore the multiple tracer provider use case, and use the Resource from the global TracerProvider, and add its attributes as process tags.
* Other languages (Python and Go) merge resource labels into span attributes rather than exporting them as process tags. We could decide to do the same. See:
  * https://github.com/open-telemetry/opentelemetry-python/blob/master/exporter/opentelemetry-exporter-jaeger/src/opentelemetry/exporter/jaeger/__init__.py#L200
  * https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/jaeger.go#L224-L230

**Comment by genebean** [comment]
For what it’s worth, I like the idea of being consistent across languages. With that in mind, merge resource labels into span attributes makes sense to me.

**Comment by fbogsany** [comment]
The collector adds resource tags as process tags rather than merging them into span attributes: https://github.com/open-telemetry/opentelemetry-collector/blob/cadd49875b3bcbc6ca555b66c7d09b6d3a78bff0/translator/trace/jaeger/traces_to_jaegerproto.go#L107-L133

I think this approach makes more sense. If we're going to support multiple tracer providers, we should group spans for export by Resource and export each group as a batch with the Resource encoded as the process.

**Comment by mwear** [comment]
I'm flexible about how we solve this, but think that we should aim for consistency across languages. I opened a spec issue for discussion: https://github.com/open-telemetry/opentelemetry-specification/issues/848.
