### ISSUE TITLE
Custom span exported failed to export due invalid encoding

### ISSUE THREAD

**Issue by Asafb26** [open-telemetry/opentelemetry-ruby#317]
ref #316

**Comment by fbogsany** [comment]
What exporter failed to export? This should be fixed in the exporters.

**Comment by Asafb26** [comment]
I have a custom exporter which dump the span to Elasticsearch, I got errors after the bump about utf8 encoding issues. I see that span and trace ids should be a byte array, but IMO the trace exporters not supposed to deal with such cases, anyway its an easy fix which can be just documented in the exporter's section

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/736 is related. Most likely, we will provide both string and byte array getters. The native representation will remain byte arrays in the Ruby SDK, and convenience methods will be added to retrieve the string representation.
