### ISSUE TITLE
(Don't?) rename HTTPText to TextMap Propagator

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#331]
https://github.com/open-telemetry/opentelemetry-specification/pull/793 renamed the `HttpTextPropagator` to `TextMapPropagator`. We have a split in our implementation between `http` and `text` propagation https://github.com/open-telemetry/opentelemetry-ruby/blob/7a10db9dea62b7cf109cd192f742a06a32554162/api/lib/opentelemetry/context/propagation/propagation.rb#L12-L19

https://github.com/open-telemetry/opentelemetry-ruby/blob/7a10db9dea62b7cf109cd192f742a06a32554162/sdk/lib/opentelemetry/sdk/configurator.rb#L130-L135

because we need to support Rack extractors for HTTP:

https://github.com/open-telemetry/opentelemetry-ruby/blob/7a10db9dea62b7cf109cd192f742a06a32554162/sdk/lib/opentelemetry/sdk/configurator.rb#L149-L154

vs

https://github.com/open-telemetry/opentelemetry-ruby/blob/7a10db9dea62b7cf109cd192f742a06a32554162/sdk/lib/opentelemetry/sdk/configurator.rb#L163-L168

I don't think we should change anything in our implementation, since the Ruby HTTP ecosystem really requires this distinction (almost?) everywhere. I'm just creating this issue to solicit and record agreement.

cc @mwear

**Comment by mwear** [comment]
I agree it's useful to have http and text versions of the propagators readily available due to Rack. I'm wondering if we could "meet in the middle" by calling our TextInjector / Extractor a TextMapInjector / Extractor. We could keep the http and text distinction, but the types would line up with the spec. I'm also fine with keeping things as-is.

**Comment by fbogsany** [comment]
>  I'm wondering if we could "meet in the middle" by calling our TextInjector / Extractor a TextMapInjector / Extractor

👍 sounds good to me -- I'll PR that, perhaps tomorrow.
