### ISSUE TITLE
Optionally trim attribute keys & values?

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#339]
Related to https://github.com/open-telemetry/opentelemetry-specification/issues/504

Java provides optional attribute value truncation: https://github.com/open-telemetry/opentelemetry-java/blob/a021a59b9433691c06ab2265b4c574eab825b0ed/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java#L195-L197
```java
    if (traceConfig.shouldTruncateStringAttributeValues()) {
      value = StringUtils.truncateToSize(value, traceConfig.getMaxLengthOfAttributeValues());
    }
```

We have some ad-hoc truncation and UTF8 validation in the Redis instrumentation, for example: https://github.com/open-telemetry/opentelemetry-ruby/blob/1a680bbd489eee18cdf78b24a99e3cc0333c41e5/instrumentation/redis/lib/opentelemetry/instrumentation/redis/utils.rb#L60-L80

It is likely worth extracting this into a common utility module, and implementing attribute truncation in a single place with a configurable limit (most likely in the SDK `Span` class).

**Comment by plantfansam** [comment]
I believe this issue [has been addressed](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/span.rb#L350-L356). Should we close or is there more to do here?

**Comment by fbogsany** [comment]
I think #1136 is relevant here.
