### ISSUE TITLE
API: implement Span.add_lazy_event

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#36]
[Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#add-events). Need to decide whether to provide an `Event` interface or a concrete `Event` class and an `EventFormatter`.

**Comment by mwear** [comment]
Similarly to `Link`, the specification doesn't define the API for an `EventFormatter`, so I'm not sure what a concrete `Event` class with an `EventFormatter` would look like. I opened this issue for clarification: https://github.com/open-telemetry/opentelemetry-specification/issues/222.
