### ISSUE TITLE
API: implement Span.add_lazy_link

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#37]
[Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#add-links). Need to decide whether to provide a `Link` interface or a concrete `Link` class and a `LinkFormatter`.

**Comment by mwear** [comment]
The specification doesn't define the API for a `LinkFormatter`, so I'm not sure what a concrete `Link` class with a `LinkFormatter` would look like. I opened this issue for clarification: https://github.com/open-telemetry/opentelemetry-specification/issues/222.
