### ISSUE TITLE
Docs for Jaeger collector exporter are wrong

### ISSUE THREAD

**Issue by genebean** [open-telemetry/opentelemetry-ruby#378]
The docs at https://github.com/open-telemetry/opentelemetry-ruby/tree/master/exporter/jaeger don't include the `/api/traces` path that is required via 
https://github.com/open-telemetry/opentelemetry-ruby/blob/ed28a6bc2a7ce7cfcad9c2940c596a651d9a6782/exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb#L18

Either the docs are wrong or the initial setting of the endpoint needs updating to append that path automatically.

**Comment by ericmustin** [comment]
i think a few exporter docs have issues at the moment actually , otlp collector exporter has a code example using incorrect args i believe https://github.com/open-telemetry/opentelemetry-ruby/tree/master/exporter/otlp#how-do-i-get-started 

Maybe we should group these all as one chunk of cleanup work

**Comment by genebean** [comment]
#427 will take care of the original issue listed here but does not address the otlp exporter docs.

**Comment by rydzykje** [comment]
Will be happy to help with that :)

**Comment by fbogsany** [comment]
Thanks @rydzykje - I've assigned this to you.

**Comment by inductor** [comment]
@ rydzykje what's up

**Comment by vsrnth** [comment]
opened #986 to fix the otlp exporter docs.
