### ISSUE TITLE
OpenTelemetry::SDK::Resources::Constants appears to be undocumented

### ISSUE THREAD

**Issue by genebean** [open-telemetry/opentelemetry-ruby#379]
When setting up the new `Jaeger::CollectorExporter` I came across `OpenTelemetry::SDK::Resources::Constants::SERVICE_RESOURCE[:name]` in its readme. I have not found any docs on this other than in its source code. 

A readme in `sdk/lib/opentelemetry/sdk/resources` might be a good way to fix this.

**Comment by fbogsany** [comment]
TBH, this is a terrible way to access this constant - for this one specifically, I think a helper in the configurator is justified:
```ruby
c.service_name = 'my-service'
```

**Comment by genebean** [comment]
There are a few in there that helpers might be nice for. The main one besides name is the one for an app’s version.

**Comment by genebean** [comment]
I think this should be reopened as there are still a lot of constants that need to be documented.

**Comment by robertlaurin** [comment]
I may have eagerly closed this out, the constants are documented here https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions

Do you think that additional documentation should live within this repo?

**Comment by genebean** [comment]
I do. Even if it is just a readme that points to the spec. There is no way the average user would know to go hunt that down in it's current home.

**Comment by fbogsany** [comment]
Closing this for now. The spec now requires a semantic-conventions package to be autogenerated from the semantic conventions YAML files in the spec. We've implemented this and removed the constants from the SDK gem.
