### ISSUE TITLE
Allow suppressing install messages

### ISSUE THREAD

**Issue by robertlaurin** [open-telemetry/opentelemetry-ruby#382]
[These](https://github.com/robertlaurin/opentelemetry-ruby/blob/6cec1d30400191c0d6e6dc54c4f71f4d211e9322/api/lib/opentelemetry/instrumentation/registry.rb#L75-L84) install messages create a lot of noise if you're doing something like repeatedly running a test suite in dev.  It would be nice to have it so we could make this optional.

**Comment by mwear** [comment]
Is configuring a no-op logger a possibility?

**Comment by genebean** [comment]
+1 to being able to suppress these.

**Comment by robertlaurin** [comment]
https://github.com/open-telemetry/opentelemetry-ruby/pull/831
