### ISSUE TITLE
Add Kubernetes resource detection

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#385]
JS does this as part of the GCP resource detection, which doesn't seem quite right: https://github.com/open-telemetry/opentelemetry-js/blob/40242aef5f0805cc6eba369faa642f9172bf24b2/packages/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts#L67-L82

**Comment by robertlaurin** [comment]
We're doing the same thing 🙃 
https://github.com/open-telemetry/opentelemetry-ruby/blob/master/resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb#L32-L38

**Comment by fbogsany** [comment]
🤔 interesting! @mat-rumian are you running your service in GKE or somewhere else? Also, I'm not having much luck finding the Python implementation of resource detectors for GCP - I don't know where the `k8s.*` attributes are coming from there.

@robertlaurin our implementation differs slightly from the JS implementation - they read the values (mostly) from environment variables. I think ours is "more correct", but it isn't working in Mat's environment. Let's hear from him before we decide how to deal with it.

**Comment by mat-rumian** [comment]
@fbogsany I'm running my service @ AWS EKS Cluster - I have few applications intrumented by OpenTelemetry: java, python, dotnet and ruby. Only ruby in configuration: `app - OTLP ->  otel-collector-contrib(with k8s_tagger processor) ` is not generating k8s tags. All other instrumentations like java, python, dotnet do - k8s tags like `k8s.namespace, k8s.container.name` are present

**Comment by mwear** [comment]
We don't currently have resource detection for AWS, but it's in our backlog. See #291.

**Comment by genebean** [comment]
I am in GKE and not seeing any k8s stuff with my traces, though I'd love to. Happy to help test if I need to turn on something for the resource detector to be activated.

**Comment by genebean** [comment]
I deployed this today and got back several resources about the host, cloud, and k8s.
