### ISSUE TITLE
API: constrain measure names to be printable and 255 chars or less

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#39]
The [Java API](https://github.com/open-telemetry/opentelemetry-java/blob/861f4e6c551f560c03d69a34829dcdd13461493b/api/src/main/java/io/opentelemetry/metrics/DefaultMeter.java#L78-L83) constrains measure names to be printable and <= 255 chars. This isn't part of the spec, but perhaps it is supposed to be?

**Comment by mwear** [comment]
I noticed similar restrictions in the [Java Resource](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/resources/Resource.java#L38-L42) implementation. I would say we should only add them if they are intended to be part of the spec.

**Comment by mwear** [comment]
Is this worthy of the question label? I added it because I think it probably is.
