### ISSUE TITLE
Don't require branches to be up to date before merging?

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#395]
The screenshot at https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md has "Require branches to be up to date before merging" checked, but it isn't explicitly listed in the policies for a new repo. We have it set on our repo, and it is causing a bit of friction with documentation PRs in particular (which are coming in thick & fast now).

Should we turn this off? @dazuma @mwear

**Comment by mwear** [comment]
I know this is on for other OpenTelemetry repos as well. I'm not sure what the potential consequences for turning it off would be. For the most part, we have the ability to merge master into PRs, but it seems like some user settings prevent this. Do you know what setting that is by chance?

**Comment by fbogsany** [comment]
The branches are in a fork https://github.com/open-o11y/opentelemetry-ruby. This appears to be an org setup by AWS for their interns working on OTel. My guess is that we need to be members of the org to be able to update their branches.

**Comment by mwear** [comment]
I think we want branches to be up to date before merging PRs with code changes, but this shouldn't be an issue for documentation changes.

**Comment by fbogsany** [comment]
We don't have the granularity of control to force this for code changes, but not for docs. I'll close this issue for now. If we get a flurry of doc changes again, I may temporarily disable this setting while I merge all the doc PRs.

**Comment by mwear** [comment]
👍 It's definitely inconvenient for docs only changes. I'd support temporarily changing the setting while handling a batch of docs PRs.
