### ISSUE TITLE
Implement OTEL_PROPAGATORS environment variable

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#412]
See: https://github.com/open-telemetry/opentelemetry-specification/pull/962

Propagators to be used as a comma separated list.

Default is "tracecontext,baggage".

> Known values for OTEL_PROPAGATORS are: "tracecontext", "baggage", "b3", "jaeger"

**Comment by akp2603** [comment]
Hi @fbogsany !
I am pretty new to open source. But I have a decent experience with rails development. Let me know if I can help with this. Would love to work on this.

**Comment by fbogsany** [comment]
Thanks @akp2603 - I've assigned you.

**Comment by mwlang** [comment]
@fbogsany I can take on this one, esp. now that I see @mwear has added B3 implementation, so what to do makes more sense now.  What I'm not sure about is how changes to configurator to support this plays with #438

**Comment by fbogsany** [comment]
Thanks @mwlang. I've assigned it to you. We don't have anything concrete around #438 yet, so I wouldn't worry about that, except to make a note of any pain points you experience in trying to implement this.
