### ISSUE TITLE
Add peer.service tag to instrumentation, where possible

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#421]
The [general semantic conventions include a `peer.service` tag](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md#general-remote-service-attributes):

> Users can define what the name of a service is based on their particular semantics in their distributed system. Instrumentations SHOULD provide a way for users to configure this name.

Description:
> The service.name of the remote service. SHOULD be equal to the actual [service.name](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/README.md#service) resource attribute of the remote service if any.

This is important in some tracing backends for inferring services such as Redis and memcached, which themselves are not traced. We depend on this heavily at Shopify. Our approach in our auto-instrumentation has been to concatenate the traced service name with the type of inferred service, e.g. `shopify:memcached`. I don't know if that's a great default in general. If not, we should certainly allow it to be overridden (and we would override it in our wrapper gem).

**Comment by robertlaurin** [comment]
I've added this everywhere I think it made sense to do so, did I miss any spots, should we keep this issue open?

**Comment by fbogsany** [comment]
- [ ] faraday (should probably use `OpenTelemetry::Common::HTTP::ClientContext.attributes`)
- [ ] excon (should probably use `OpenTelemetry::Common::HTTP::ClientContext.attributes`)
- [ ] ethon (should probably use `OpenTelemetry::Common::HTTP::ClientContext.attributes`)
- [ ] mongo
- [ ] restclient (should probably use `OpenTelemetry::Common::HTTP::ClientContext.attributes`)

**Comment by fhwang** [comment]
@robertlaurin Do you mind if I take on a few of these?

**Comment by robertlaurin** [comment]
@fhwang please do 😄

**Comment by fhwang** [comment]
For the HTTP instrumentations, are we saying we want to add the `peer.service` setting as an automatic value in `OpenTelemetry::Common::HTTP::ClientContext.attributes`? Just double-checking because that currently defaults to an empty hash, and I wonder if it would be surprising to have values show up there. On the other hand it's not obvious where would be a better way to put it.

**Comment by fhwang** [comment]
Thinking on it more, I suppose putting in `HTTP::ClientContext`, while it would be convenient, would be pretty confusing. I suppose what'll happen over time is we'll want to evolve towards some common utility code used by all HTTP libraries and put this sort of thing there. I'll ignore the duplication for now.

**Comment by fhwang** [comment]
The five instrumentations covered in the checklist above are all finished, should we close this one?

**Comment by fbogsany** [comment]
Thanks @fhwang!
