### ISSUE TITLE
API: Retrieve Resource labels 

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#43]
There has been some discussion on #24 about the best way to expose labels from the Resource API. This is covered in the [retrieve labels](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-resources.md#retrieve-labels) section of the Resource spec.

We are currently exposing an enumerator and not the underlying frozen hash of labels. Exposing the underlying hash would require that all SDKs would have to return labels with a data structure matching that interface. See the discussion [here](https://github.com/open-telemetry/opentelemetry-ruby/pull/24#discussion_r311232767).

Several options have been proposed:

* labels should return an enumerable, the exact implementation would be up to the SDK
* a `each_label` method
* exposing the underlying hash

If there are any other options we should add them here and discuss what we'd like to do going forward.

**Comment by fbogsany** [comment]
Is this still something we want to explore @mwear?
