### ISSUE TITLE
Propagating context for HTTP client libraries

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#443]
This issue captures a conversation @robertlaurin and I had yesterday.

Faraday is a commonly used HTTP client wrapper gem that supports stacking middleware around HTTP client requests. It can wrap a variety of HTTP clients, including `Net::HTTP` and [Typhoeus](https://github.com/typhoeus/typhoeus) (for which we should add instrumentation as well). Other gems may provide higher-level interfaces for various services, such as [Koala](https://github.com/arsduo/koala) for Facebook, built on top of Faraday.

In general, we typically want to provide a single `kind=client` span for a single HTTP client request, but each layer involved in the request may want to add information (attributes) to the span. Unfortunately, unlike HTTP server spans, the layers of the stack are inverted: the span is created and finished at the end of the call stack, so the information from middleware, etc. needs to be propagated with the calls.

Context propagation seems like the right mechanism to use for this. The problems to solve include:
1. The leaf HTTP clients have no knowledge of higher layers;
2. There are many higher-layer (e.g. Koala) and mid-layer (e.g. Faraday) gems;
3. A variety of leaf HTTP clients can be plugged into the higher- and mid-layer gems.

The only thing these components have in common is that they all relate to HTTP client requests. It would be helpful to define a common HTTP client context propagation mechanism that all layers can use. Strawman proposal:

```ruby
module HTTPClientContext
  # with_attributes merges the attributes_hash into the HTTP client context found in the optional context,
  # or in the current context if none is provided, and yields the new context.
  def with_attributes(context=nil, attributes_hash) ... end

  # attributes returns the attributes hash representing the HTTP client context found in the optional context
  # or the current context if none is provided.
  def attributes(context=nil) ... end
end
```

Example use:

```ruby
# in Koala instrumentation
HTTPClientContext.with_attributes({'peer.service' => 'facebook'}) do
  ...
end

# in Net::HTTP instrumentation
attributes = HTTPClientContext.attributes
tracer.in_span(
  HTTP_METHODS_TO_SPAN_NAMES[req.method],
  attributes: attributes.merge({
    'http.method' => req.method,
    'http.scheme' => USE_SSL_TO_SCHEME[use_ssl?],
    'http.target' => req.path,
    'peer.hostname' => @address,
    'peer.port' => @port
  }),
  kind: :client
) do |span|
  ...
end
```

**Comment by kirs** [comment]
As a note, it would be great having something similar to `HTTPClientContext` but for the Redis client (and perhaps for other adapters too).

cc @gustavocaso
