### ISSUE TITLE
Add instrumentation for Typhoeus

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#445]
https://github.com/typhoeus/typhoeus

> Typhoeus wraps libcurl in order to make fast and reliable requests.

Related: #443

**Comment by robertlaurin** [comment]
Do we still want/need instrumentation for this gem if we have `ethon` instrumention? 

It seems like typhoeus uses ethon under the hood.
https://github.com/typhoeus/typhoeus/blob/master/typhoeus.gemspec#L20

**Comment by fbogsany** [comment]
🤔 maybe not?

**Comment by robertlaurin** [comment]
Going to close this as we have a lower level lib instrumented, if an argument for having instrumentation specific to this gem is made we can re-open the issue and or accept an instrumentation PR.
