### ISSUE TITLE
GH Actions CI spamming commits 

### ISSUE THREAD

**Issue by robertlaurin** [open-telemetry/opentelemetry-ruby#449]
Encouraging the use of conventional commits makes sense but I'm concerned pinging each commit someone pushes up against a branch is a little too aggressive :)

![image](https://user-images.githubusercontent.com/23463253/97097615-5255ba00-1640-11eb-9175-84f83cde29ce.png)

https://github.com/open-telemetry/opentelemetry-ruby/pull/446#issuecomment-715890873

Hey @dazuma, you are our resident CI expert is this something you could help with?

**Comment by dazuma** [comment]
Hmm. Yeah I'll see if I can update the script not to add another comment if one has been added previously.
