### ISSUE TITLE
SDK Exporter/BatchProcessor should not hard-fail in an initializer

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/opentelemetry-ruby#464]
If you put a bad URL in to initialize an `OpenTelemetry::Exporter::OTLP::Exporter`, it fails with:

```
Unable to load application: ArgumentError: invalid url for OTLP::Exporter google.com:55681
```

The recommended Rails initializer code doesn't have any `rescue` block. We were a bit surprised when our app hard failed to boot with an invalid url. We've added the rescue block to the initializer, but I think it would be nicer if maybe OpenTelemetry::SDK.configure could rescue it's block and log an error `"OpenTelemetry failed to configure: ArgumentError: invalid url ...`

```
OpenTelemetry::SDK.configure do |c| # rescue this block
    ...
    c.add_span_processor(processor)
    c.use_all
 end
```

**Comment by fbogsany** [comment]
The current behaviour is consistent with the [error handling principles](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#basic-error-handling-principles):
> The API or SDK may _fail fast_ and cause the application to fail on initialization, e.g. because of a bad user config or environment, but MUST NOT cause the application to fail later at run time, e.g. due to dynamic config settings received from the Collector.

However I don't think we've implemented [configurable error handling](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#configuring-error-handlers):
> SDK implementations MUST allow end users to change the library's default error handling behavior for relevant errors. Application developers may want to run with strict error handling in a staging environment to catch invalid uses of the API, or malformed config. Note that configuring a custom error handler in this way is the only exception to the basic error handling principles outlined above. The mechanism by which end users set or register a custom error handler should follow language-specific conventions.

I'll add a `rescue` to `configure` with a default behaviour of log and re-`raise`, and a mechanism to install a different error handler.

**Comment by johnnyshields** [comment]
@fbogsany ok, great. Will configurable error handling also apply to tracers, etc. at runtime?

**Comment by fbogsany** [comment]
> @fbogsany ok, great. Will configurable error handling also apply to tracers, etc. at runtime?

I asked that question in #465. We've taken a stab at this before:
- The initial implementation was strict
- https://github.com/open-telemetry/opentelemetry-ruby/pull/115 removed the runtime checks
- https://github.com/open-telemetry/opentelemetry-ruby/issues/126 suggested an optional strict mode
- https://github.com/open-telemetry/opentelemetry-ruby/issues/203 discussed what to do with invalid attributes
- https://github.com/open-telemetry/opentelemetry-ruby/pull/207 was an attempt to address that, but stalled

The configurable `OpenTelemetry.logger` was our best interim solution, but it only addresses logging with the option to `raise` (and it doesn't explicitly receive the exception object), whereas in some cases (like configuration) we want a default of `raise` with the ability to disable that. I don't know the idiomatic way to do this in Ruby.
