### ISSUE TITLE
Add Lightstep exporter?

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/opentelemetry-ruby#488]
@mwear is there any propagator available for Lightstep or any beta code we could get access to? We'd like to start using Otel with Lightstep as soon as we can.

**Comment by mwear** [comment]
Hi @johnnyshields. The title says propagator, but I just want to clarify if you are asking about a Lightstep propagator, or a Lightstep exporter. I'll answer both questions just in case. There isn't a Lightstep propagator for OTel, but all Lightstep tracing clients support B3 context propagation, as do all OTel libraries. So you could use B3 to propagate context between an app using OTel Ruby and [Lightstep Tracer Ruby](https://github.com/lightstep/lightstep-tracer-ruby). If your question is about a propagator, let me know if B3 is a possible solution for you, and if not, I'd be interested to know about the use case.

As far as an exporter goes, Lightstep ingests OTLP natively. You can use the opentelemetry-exporter-otlp gem to send spans to Lightstep. If you need more instructions on how to configure it, let me know.

**Comment by johnnyshields** [comment]
@mwear sorry meant exporter! (title changed)

It would be great if you could update the documentation on the Lightstep docs site to include how to connect the Opentelemetry-ruby gem.

**Comment by johnnyshields** [comment]
I think this can be closed.

**Comment by mwear** [comment]
@johnnyshields: I'll work to get some documentation up on the Lightstep docs page. For the time being, this should be enough to get you started:

```ruby
OpenTelemetry::SDK.configure do |c|
  c.service_name = 'my-ruby-service'
  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      exporter: OpenTelemetry::Exporter::OTLP::Exporter.new(
        endpoint: 'ingest.lightstep.com:443/api/v2/otel/trace',
        insecure: false,
        headers: { 'lightstep-access-token' => ENV['LS_ACCESS_TOKEN'] }
      )
    )
  )
end
```

**Comment by sj26** [comment]
You should put these instructions somewhere more accessible, I had to hunt pretty hard for these! But OpenTelemetry is a great way to hook this up, and enables a lot more stuff than the datadog-ish or opentracing approaches suggested within Lightstep.
