### ISSUE TITLE
Support for Postgresql

### ISSUE THREAD

**Issue by jcarres-mdsol** [open-telemetry/opentelemetry-ruby#523]
Postgresql is also a very common engine used together with Ruby on Rails. 
Implement Postgresql instrumentation similar to the one for [Mysql](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb).

BTW, wouldn't it be easier to create instrumentation for ActiveRecord and Sequel than for each database or that would not give enough information?

**Comment by johnduhart** [comment]
> BTW, wouldn't it be easier to create instrumentation for ActiveRecord and Sequel than for each database or that would not give enough information?

It would, but it would miss calls that don't use an ORM.

**Comment by kbrock** [comment]
When I use rack mini profiler, I changed it  to focus on ActiveSupport notifications. Calls that do not fetch rails objects (e.g.: pluck, count, min, max) tend to not be represented well - specifically pluck not having a row_count.
But I found ActiveSupport notifications, even with that caveat, worked better for my needs and covered a majority of the use cases.

It may be possible to leverage knowledge from the monkey patches used by rack mini profiler, app profiler, bullet, or the myriad of other gems that have profiled database interactions over the years. for sure, they will highlight the difference between mysql, postgres, and other database drivers (mongo, redis?).

**Comment by theabhishekg** [comment]
Hi @kbrock, I am currently working on a task that involves comparing the traces captured between ActiveRecord instrumentation and PG instrumentation. Debating as to whether the transition from the former to the latter would be worth the effort. 

I would love to know more about what you may have uncovered using your profiler (and other gems), if you don't mind sharing. Thanks!

**Comment by kbrock** [comment]
Hi @theabhishekg

(sorry, just found a tab open with this comment in it)

I use https://github.com/MiniProfiler/rack-mini-profiler in development, but I believe discord uses that in production. It is backed by some pretty strong names (Sam was a ruby fellow) and there is even a rails cast from 2012.

If you note [sql_patches.rb](https://github.com/MiniProfiler/rack-mini-profiler/blob/f20c4c6315bcd5bbfba234fc0a65edbf30d7c165/lib/patches/sql_patches.rb#L30-L47], there are a few patching options.

They use `patch_rails?` to choose `ActiveSupport::Notifications` vs monkey patching the rails classes themselves. Quite a few years ago, New Relic rpm transitioned from patching rails directly to using notifications. I think close to when the notification framework came out. I'd even like to say there was some collaboration on that one, but that may have been my misunderstanding. Rack mini profiler has been slower to the transition away from monkey patching.

Let me know if the patch link is not crystal clear.

Keenan

Tangent:

Also, you may want to keep an eye on https://github.com/jhawthorn/vernier
Aaron paterson demoed this at Rails World 2023 https://youtu.be/GnqRMQ0iQTg?si=Mq4hYX4VmkX0EYIV&t=1228
