### ISSUE TITLE
[CLEANUP] Ruby-kafka appraisals older than 1.3 failing on Ruby 3.0

### ISSUE THREAD

**Issue by dazuma** [open-telemetry/opentelemetry-ruby#542]
We've currently disabled the `ruby-kafka-1.2.0`, `ruby-kafka-1.1.0`, and `ruby-kafka-1.0.0` appraisals in the `opentelemetry-instrumentation-ruby_kafka` tests because they are causing the following failure:

```
OpenTelemetry::Instrumentation::RubyKafka::Patches::Producer::tracing#test_0002_traces async produce calls:
RuntimeError: Max wait time exceeded for async producer
    /__w/opentelemetry-ruby/opentelemetry-ruby/instrumentation/ruby_kafka/test/test_helper.rb:29:in `wait_for'
    /__w/opentelemetry-ruby/opentelemetry-ruby/instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/producer_test.rb:66:in `block (3 levels) in <top (required)>'
```

`ruby-kafka-1.3.0` seems to be working.

We need to investigate why the test is failing. It may be that the older versions of the library are incompatible with Ruby 3 (in which case we can leave those appraisals disabled on Ruby 3), or it may be that our test needs to be updated.

**Comment by robertlaurin** [comment]
It appears that older version of `ruby-kafka` are not compatible with Ruby 3 due to the changes regarding positional and keyword args.

Example from [Version 1.3.0](https://github.com/zendesk/ruby-kafka/blob/v1.3.0/lib/kafka/async_producer.rb#L220)
Example from [Version 1.2.0](https://github.com/zendesk/ruby-kafka/blob/v1.2.0/lib/kafka/async_producer.rb#L211)

```rb
/.gem/ruby/3.0.0/gems/ruby-kafka-1.2.0/lib/kafka/async_producer.rb:213 Kafka::AsyncProducer::Worker#run:
    208:           operation, payload = @queue.pop
    209:
    210:           case operation
    211:           when :produce
    212:             binding.pry
 => 213:             produce(*payload)
    214:             deliver_messages if threshold_reached?
    215:           when :deliver_messages
    216:             deliver_messages
    217:           when :shutdown
    218:             begin
[1] pry(#<Kafka::AsyncProducer::Worker>)> payload
=> ["hello async", {:topic=>"async-topic-e1b43909-997b-4a58-a09b-fa4a85f54d87"}]
[2] pry(#<Kafka::AsyncProducer::Worker>)> produce(*payload)
ArgumentError: wrong number of arguments (given 2, expected 1)
from /Users/robertlaurin/.gem/ruby/3.0.0/gems/ruby-kafka-1.2.0/lib/kafka/async_producer.rb:251:in `produce'
```

So it looks like we should just leave those appraisals disabled.
