### ISSUE TITLE
Release process is error-prone and cumbersome

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#543]
The last few releases have failed early, typically with an error retrieving the `thrift` gem for the Jaeger exporter. Because the Jaeger exporter is early (4th) in the list of gems to build, the release aborts with the majority of gems unreleased. The unreleased gems have to be released manually, one at a time, which is quite cumbersome.

A simple improvement would be to move the Jaeger exporter to the end of the list of gems to release, so its errors only affect that one gem.

A larger improvement would be to support restarting the release, skipping over already released gems.

**Comment by dazuma** [comment]
I'm actually on it; I worked on a retry-release action over the holiday, and just need to finish testing it before rolling it out to the otel repo.

**Comment by fbogsany** [comment]
You're amazing @dazuma - thank you!
