### ISSUE TITLE
SDK: Thread safety

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#6]
[LightStep's Ruby gem](https://github.com/lightstep/lightstep-tracer-ruby) is thread-safe. For example, spans can be modified concurrently in different threads (adding tags, logs, etc.).

The [OpenCensus Ruby gem](https://github.com/census-instrumentation/opencensus-ruby) is not thread-safe. Spans cannot be safely shared between threads.

Should we support this use-case (concurrent modification of a span)?

**Comment by bogdandrutu** [comment]
I would suggest that we need to be thread safe.

**Comment by luong-komorebi** [comment]
+1 for this usecase

**Comment by luong-komorebi** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/concurrency.md

**Comment by benedictfischer09** [comment]
The spec has info about which apis must be threadsafe and which are not https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/concurrency.md

**Comment by fbogsany** [comment]
Yep, this issue predated the spec’s text on thread safety. Closing.
