### ISSUE TITLE
SDK: Implement BatchSampledSpanProcessor

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#64]
https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/lib/opentelemetry/sdk/trace/export/batch_sampled_span_processor.rb

**Comment by fbogsany** [comment]
Roughly model on the Java implementation here: https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSampledSpansProcessor.java

**Comment by fbogsany** [comment]
#74

**Comment by rdooley** [comment]
I have also done some work on this

**Comment by rdooley** [comment]
I think this was settled in #74 
I cannot close however

**Comment by fbogsany** [comment]
Fixed in #74
