### ISSUE TITLE
HTTP Span Attributes: `http.url` must not contain username / password

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-ruby#647]
As is stated in the recent [specification change](https://github.com/open-telemetry/opentelemetry-specification/pull/1502) :

> `http.url` MUST NOT contain credentials passed via URL in form of `https://username:password@www.example.com/`. In such case the attribute's value should be `https://www.example.com/`

**Comment by fbogsany** [comment]
Thanks for the issue. I confirmed 2 of our instrumentations violate this requirement. I've pushed up tests in #648 and I'll work on a fix.
