### ISSUE TITLE
Obscure configuration error

### ISSUE THREAD

**Issue by sj26** [open-telemetry/opentelemetry-ruby#664]
My first experience with this gem was:

```
E, [2021-03-18T04:14:42.145080 #24298] ERROR -- : OpenTelemetry error: unexpected configuration error - OpenTelemetry::SDK::ConfigurationError
```

There was an error in my configuration, which was roughly copied from an example in an issue within this repository:

```
OpenTelemetry::SDK.configure do |config|
  config.service_name = "..."
  config.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      exporter: OpenTelemetry::Exporter::OTLP::Exporter.new(
        endpoint: "ingest.lightstep.com:43/api/v2/otel/trace",
        insecure: false.
        headers: { "lightstep-access-token" => ENV.fetch("LIGHTSTEP_TOKEN") }
      )
    )
  )
end 
```

It was revealed when I wrapped it to output more information about the exception:

```
OpenTelemetry::SDK.configure do |config|
  begin
    config.service_name = "..."
    config.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        exporter: OpenTelemetry::Exporter::OTLP::Exporter.new(
          endpoint: "ingest.lightstep.com:43/api/v2/otel/trace",
          insecure: false.
          headers: { "lightstep-access-token" => ENV.fetch("LIGHTSTEP_TOKEN") }
        
      )
    )
  rescue
    puts "#{$!.class.name}: #{$!}", *$!.backtrace 
    raise
  end
end 
```

(it was `unknown keyword: :insecure`)

Perhaps whatever is logging this error should provide more context?

**Comment by fbogsany** [comment]
The problem is that we're rescuing any errors during configuration and instead raising a ConfigurationError (to allow users to supply their own error handling, and to distinguish config errors from errors that occur elsewhere), but in doing so, we discard the original error. It *is* available from `e.cause`, but we should probably just report information from it directly.

Thanks for raising the issue - I'll fix this today.

**Comment by sj26** [comment]
Thanks fbogsany, I see the adjustments! 🥳 

It's not quite what I had in mind, though. The new implementation still avoids displaying a stack trace, or the causing error class.

Instead I'd propose appending the exception's `#full_message` in opentelemetry's default error_handler which would reveal the full exception's details including class, message, backtrace, and the chain of causal exceptions' details as well:

**Comment by fbogsany** [comment]
The default `error_handler` is intended to be called in a wide variety of contexts. We need to balance verbosity with clarity, and we want to avoid spewing tons of stack traces into logs if someone uses the APIs incorrectly. It may be useful to provide a verbose `error_handler` as an option in the configuration or in `opentelemetry-common`, but I don't see us making that the default.
