### ISSUE TITLE
SDK: fork safety

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#7]
[LightStep's Ruby gem](https://github.com/lightstep/lightstep-tracer-ruby) is fork-safe. If a process forks, spans already buffered in memory by the parent process are not exported by the child process.

Do we want to support `fork()`? Doing so brings some complexity. It isn't clear that common use-cases for tracing require it.

**Comment by bogdandrutu** [comment]
New in Ruby world is this a classic fork and exec pattern?

**Comment by indrekj** [comment]
Had to do something similar in the [Jaeger](https://github.com/salemove/jaeger-client-ruby/blob/master/lib/jaeger/reporters/remote_reporter.rb#L29) ruby gem. I didn't need this myself, but it seems that pre-forking app servers is common and some people do find it useful.

**Comment by fbogsany** [comment]
There's a few challenges with `fork()` and tracing:
1. Exporters using gRPC (such as the OpenCensus agent exporter) will need to carefully close and reopen connections to avoid crashing in the child process.
2. Either the global PRNG (`Random::DEFAULT`) will need to be used everywhere or any other `Random` instance will need to be reseeded after `fork()`. MRI reseeds the global instance at fork, but continued use of other instances in pre-forked app servers will lead to duplicate trace IDs (we have recent scars from this).
3. Any buffered `SpanData` will need to be dropped in child processes. This requires detecting that a `fork()` has occurred and the PID used to enqueue a `SpanData` differs from the current PID.
4. For pre-forking app servers (and job workers in Sidekiq or Resque), it is most robust to enable exporters after `fork()`, however the hooks for this differ between frameworks and typically require manual configuration (they're not amenable to monkey-patching).
5. Do we want/need to support tracing in the master process for these servers? Doing so adds some complexity. It is achievable, but will likely require manual intervention.

I'd like to bias design decisions to automatic initialization, configuration and instrumentation, so the default experience is that everything "just works". Our internal tracing gem at Shopify works this way for Rails applications, but relies on additional tooling to automatically create a PR to add tracing, which adds both the gem and an initializer. We shouldn't assume that tooling in the OpenTelemetry gem.

**Comment by johnnyshields** [comment]
👍 to adding safe forking. Puma 5.0 introduced forking from an active child worker and it re-forks every 1000 requests, so I think issues with duplicating in-process spans are bound to happen with the BSP. Refer to: https://github.com/puma/puma/blob/master/docs/fork_worker.md

**Comment by fbogsany** [comment]
The BSP is fork-safe. If you have an example in the wild demonstrating that isn't true, and can reduce it to a minimal test case, then please open an issue.

For the challenges I mentioned previously:

1. We have no gRPC exporters at present, so this is a problem for future us.
2. We're using `Random::DEFAULT` for trace and span ID generation, and MRI reseeds this at fork.
3. The BSP is fork-safe and will drop buffered spans in child processes.
4. The BSP has a `start_thread_on_boot:` option (`OTEL_RUBY_BSP_START_THREAD_ON_BOOT` env var) that helps delay thread creation until after `fork()`. The existing exporters (OTLP/HTTP, Jaeger agent and collector) are initialized eagerly, but connect lazily.
5. 🤷

**Comment by johnnyshields** [comment]
@fbogsany then can this issue be closed?
