### ISSUE TITLE
API Tracer auto-promotion to SDK Tracer

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#706]
Currently, if a `Tracer` instance is requested from `OpenTelemetry.tracer_provider` before the SDK is installed, a no-op API `Tracer` is returned. This instance will create no-op API `Span` instances in `#start_span`. Those spans will not be recorded, thereby breaking traces (child and parent spans may be recorded if their `Tracer` instances are "real" SDK tracers).

This is going to be a common situation for first-party instrumentation (e.g. if the `redis` gem is instrumented directly rather than being patched by the `opentelemetry-instrumentation-redis` gem).

We should consider "promoting" API `Tracer` instances to SDK `Tracer` instances when the SDK is installed (this should be true even if an SDK other than `opentelemetry-sdk` is installed).

## Things to consider:
- [x] Survey other language SIGs to see how they handle this situation (proxy tracers?)
- [ ] What's the performance impact of always checking the global `tracer_provider` and forwarding?
- [x] Smalltalk's `#become:` would be lovely here, but this is Ruby 😞 
- [ ] We should only adapt API `Tracer` instances returned by the global `OpenTelemetry.tracer_provider` - perhaps this means we want to introduce special `GlobalTracerProvider` and `ProxyTracer` classes in the API? If someone steps off the beaten path and explicitly creates a `TracerProvider` that returns API `Tracer` instances, those `Tracer` instances should *NOT* be promoted
- [ ] Should we move span creation to the `TracerProvider`? If so, we need to document this behaviour for other SDK implementations to follow
- [ ] Whatever we do here, if it adds API, should be clearly documented for both users and other SDK implementations

**Comment by fbogsany** [comment]
## Survey of other language SIGs

Go has a default `TracerProvider` implementation that delegates `Tracer` calls once the "real" `TracerProvider` is installed. It returns `Tracer` instances that delegate as well, after the "real" `TracerProvider` is installed: https://github.com/open-telemetry/opentelemetry-go/blob/main/internal/global/trace.go

Swift doesn't do anything special.

Python has a `ProxyTracerProvider` and `ProxyTracer` similar to Go. Unlike Go's implementation, it only permits the global tracer provider to be set once: https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/trace/__init__.py

JS has a `ProxyTracerProvider` and a similar registration process to plugin the real one: https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/api/trace.ts

C++ doesn't do anything special.

Java doesn't appear to do anything special. It only allows the `TracerProvider` to be set once. It tries to initialize the SDK early through reflection, and otherwise recommends that the SDK be configured as early as possible.

Rust does not seem to do anything special.

.NET does not seem to do anything special.

**Comment by fbogsany** [comment]
## Questions

- [ ] Should we permit the global `TracerProvider` to be set only once or many times?
- [ ] Should the default `Tracer` and `TracerProvider` instances be upgraded once or repeatedly (i.e. should they delegate to an instance variable or to whatever global instance is currently installed)?

**Comment by arielvalentin** [comment]
> Implementations MUST NOT require users to repeatedly obtain a Tracer again with the same name+version to pick up configuration changes. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer

This language seems to imply that the `Tracer` object instance must inherit the traits of any configuration changes, which I assert would mean the Tracer would likely need to have it's underlying implementation changed in a thread-safe way. 

I have not read the spec very closely but what is unclear to me here is how this `Tracer` should behave if it is "switched" in mid-trace. E.g. if a trace is started by a no-op tracer and then the tracer is promoted, should the child span be generated by the newer configuration or the previous config?

> Notwithstanding any global TracerProvider, some applications may want to or have to use multiple TracerProvider instances, e.g. to have different configuration (like SpanProcessors) for each (and consequently for the Tracers obtained from them), or because its easier with dependency injection frameworks. Thus, implementations of TracerProvider SHOULD allow creating an arbitrary number of TracerProvider instances.

Hmm... so does that mean we should only be updating a `Tracer` and not a `TracerProvider`? And does that mean a `Tracer` can be upgraded in _any_ tracer provider at any point?

**Comment by fbogsany** [comment]
> I have not read the spec very closely but what is unclear to me here is how this `Tracer` should behave if it is "switched" in mid-trace. E.g. if a trace is started by a no-op tracer and then the tracer is promoted, should the child span be generated by the newer configuration or the previous config?

The tracer really only participates in span creation. If a tracer is "promoted" mid-trace, then the trace will be broken (valid child spans may be created and recorded with a no-op parent span). This is an acceptable risk IMO because the alternatives are: create valid spans all the time, even if they're not going to be exported; or *don't* promote tracers and potentially always have broken traces.

In practice, the configuration described in this part of the spec  is picked up from the tracer provider (e.g. changing the sampler), and the spec suggests that this may be achieved by keeping a reference from the tracer to the tracer provider that created it.

> > Notwithstanding any global TracerProvider, some applications may want to or have to use multiple TracerProvider instances, e.g. to have different configuration (like SpanProcessors) for each (and consequently for the Tracers obtained from them), or because its easier with dependency injection frameworks. Thus, implementations of TracerProvider SHOULD allow creating an arbitrary number of TracerProvider instances.
> 
> Hmm... so does that mean we should only be updating a `Tracer` and not a `TracerProvider`? And does that mean a `Tracer` can be upgraded in _any_ tracer provider at any point?

This is the "escape hatch" that we talked about on the call. If you create several TracerProviders that are *not* installed as the global tracer provider, then you're off the beaten path, you presumably know what you're doing, and we're not going to mess with your tracer providers under the covers.

The only case we care about here is the "golden path" of acquiring tracers from the global tracer provider, where some of those tracers may be acquired before a SDK (not necessarily *the* SDK) has installed itself.

**Comment by arielvalentin** [comment]
> This is the "escape hatch" that we talked about on the call. If you create several TracerProviders that are not installed as the global tracer provider, then you're off the beaten path, you presumably know what you're doing, and we're not going to mess with your tracer providers under the covers.
> The only case we care about here is the "golden path" of acquiring tracers from the global tracer provider, where some of those tracers may be acquired before a SDK (not necessarily the SDK) has installed itself.

Understood, but I think this constraint still applies though in those scenarios as well:

> Implementations MUST NOT require users to repeatedly obtain a Tracer again with the same name+version to pick up configuration changes. This can be achieved either by allowing to work with an outdated configuration or by ensuring that new configuration applies also to previously returned Tracers.

**Comment by fbogsany** [comment]
It does. The API tracer provider has no configuration state, whereas the SDK tracer provider *does* have config state. The SDK tracers keep a reference to the tracer provider that created them. If you look at #708 the proxy tracer will delegate to a corresponding SDK tracer after the SDK tracer provider is plugged in. This is done behind the scenes and does not require the user to acquire a tracer again with the same name+version.
