### ISSUE TITLE
Emit Honeycomb API marker events using this library

### ISSUE THREAD

**Issue by diclophis** [open-telemetry/opentelemetry-ruby#716]
Is it possible to relay these types of events: https://docs.honeycomb.io/api/markers/ through otel+otlp ... that is to say, is there an otel equivalent for honeycomb "markers"?

**Comment by fbogsany** [comment]
I think that's a question for Honeycomb. This might be relevant: https://www.honeycomb.io/blog/uniting-tracing-logs-open-telemetry-span-events/. I don't know whether Span Events would map to Markers. If so, you'd use `span.add_event(...)`.

**Comment by robbkidd** [comment]
Span events—a child event of a specific span—will definitely not behave like [Markers](https://docs.honeycomb.io/working-with-your-data/customizing-your-query/markers/) which are cross-cutting to allow for annotating a timeline. I understand there are some folks working on a submission to add the concept to OpenTelemetry spec.

**Comment by robbkidd** [comment]
I'd propose closing this issue until a time that the OpenTelemetry spec includes a concept equivalent to a Honeycomb Marker. I think until it is in the spec, Markers-or-whatever-they-are-named are out of scope for this API/SDK.

**Comment by diclophis** [comment]
ok thanks @robbkidd / @arielvalentin / @fbogsany  ... I will keep my eye on the specification, you are correct in that it would not be proper just yet to include any vendor specific features into the library before they were standardized.
