### ISSUE TITLE
Wrong exporter selected for jaeger in OTEL_TRACES_EXPORTER

### ISSUE THREAD

**Issue by treyhyde** [open-telemetry/opentelemetry-ruby#728]
I believe, based on https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection, that selecting `jaeger` for `OTEL_TRACES_EXPORTER` should use the agent exporter, not the collector exporter as set in https://github.com/open-telemetry/opentelemetry-ruby/blob/b7149fb72cad6c45956a6be80acfb2d062aab3a6/sdk/lib/opentelemetry/sdk/configurator.rb#L153

**Comment by fbogsany** [comment]
Technically, it is supposed to be the gRPC exporter, which we don't support. The closest equivalent is the `CollectorExporter`, not the `AgentExporter`.

**Comment by treyhyde** [comment]
I would love a way to select the AgentExporter which is the extreme preference with the OTEL environment variables.   The `jaeger` value delivers to the agent in my other language stacks.  Having consistency here in the otel community would be of great value.

**Comment by fbogsany** [comment]
> The `jaeger` value delivers to the agent in my other language stacks.

It sounds like those aren't compliant with the spec, then. Unless they're using gRPC to the agent?

If someone adds a Jaeger exporter with gRPC support, we'll update the environment variable handling to use that. In the meantime, maybe we could add a `jaegeragent` value to configure the agent exporter?
