### ISSUE TITLE
API: Propagate tracestate 

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#73]
There was a  PR to [temporarily remove `tracestate`](https://github.com/open-telemetry/opentelemetry-specification/pull/198). It was opened due to confusion around what context belongs in tracestate, but ultimately never merged. The [Context Propagation OTEP](https://github.com/open-telemetry/oteps/pull/42) provides the necessary layers for the different types of context that users can interact with. It doesn't mention tracestate, and that is because tracestate is for context used by the tracer (SDK) implementation.

As discussed in a recent W3 Distributed Tracing Meeting OpenTelemetry should:

* Propagate tracestate
* Does not need to expose it via API
* May expose it via SDK SPI if there is a use case

**Comment by fbogsany** [comment]
The spec states:

> `SpanContext` MUST be a final (sealed) class.

`SpanContext` is specified in the API, and currently contains the `tracestate`. How should this be hidden from the API but exposed (possibly) in the SDK and propagated?

**Comment by mwear** [comment]
Those words are from the [meeting notes](https://docs.google.com/document/d/12AAIbnkt_AH1YjZwUwxirX_7WA7aWOSXpDweCgfqIiQ/edit#) on 2019-09-10. I believe the intent is that trace state is for context needed for a tracing vendor and not for end users. So, it does need to be exposed on the SpanContext so that tracing vendors other SDK implementations can interact with it, but it should not be exposed to end users. This probably means that will be "protected" by a comment in the code, and not a language construct.

**Comment by fbogsany** [comment]
Fixed in #136
