### ISSUE TITLE
Encoding::UndefinedConversionError in Jaeger's CollectorExporter

### ISSUE THREAD

**Issue by chrisholmes** [open-telemetry/opentelemetry-ruby#751]
One of my team's services went live with Otel, but we're seeing frequent but low volume encoding errors in the `Jaeger::CollectorExporter`

Here's an example:
```
Encoding::UndefinedConversionError:  "\xF6" from ASCII-8BIT to UTF-8
/gems/thrift-0.14.1/lib/thrift/bytes.rb:81 in encode
/gems/thrift-0.14.1/lib/thrift/bytes.rb:81 in convert_to_utf8_byte_buffer
/gems/thrift-0.14.1/lib/thrift/protocol/binary_protocol.rb:110 in write_string
/gems/thrift-0.14.1/lib/thrift/serializer/serializer.rb:29 in write
/gems/thrift-0.14.1/lib/thrift/serializer/serializer.rb:29 in serialize
/gems/opentelemetry-exporter-jaeger-0.16.0/lib/opentelemetry/exporter/jaeger/collector_exporter.rb:45 in block in export
/gems/opentelemetry-exporter-jaeger-0.16.0/lib/opentelemetry/exporter/jaeger/collector_exporter.rb:44 in each
/gems/opentelemetry-exporter-jaeger-0.16.0/lib/opentelemetry/exporter/jaeger/collector_exporter.rb:44 in export
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186 in block in export_batch
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186 in synchronize
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186 in export_batch
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:169 in block in work
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:158 in loop
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:158 in work
/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:179 in block in reset_on_fork
```

This service deals with Kafka messages from other services and after some reasoning through our codebase I'm confident that the data that triggers this exception comes from these messages. However, I can't place which attribute or other property would contain characters that can't be converted.

The non-utf-8 compliant characters change error-by-error so it's possible that this data might come from using a byte string in the wrong place.

I could possibly add some logging to wrap around the CollectorExporter and prints out spans that contain the non-utf8 compliant characters, but I'm hoping to avoid logging if I can.

Ideally, I'd like to consider having the Jaeger::Encoder convert all strings to UTF-8 before they're converted into thrift format. Is there appetite for this?

**Comment by arielvalentin** [comment]
I could be mistaken here but that error seems to indicate to me that the `String` object is a `BINARY` object and not a `Text` encoding. Forcing the encoding of a `BINARY` attribute into `UTF-8` text encoding may result in even stranger results since I do not think the value is meant to be interpreted as text. 

Are you all dynamically adding tags based on data in the Kafka message here? Do those messages contain binary objects as values instead of text?

**Comment by chrisholmes** [comment]
Nope, we haven't done anything extra with these spans.

It's possible that we're receiving messages that contain binary data in pre-instrumented fields, but I'd have to add that logging to be sure. However, I'm assuming that the instrumentation, or another part of these libraries, would want to protect against this kind of thing.

**Comment by fbogsany** [comment]
> Ideally, I'd like to consider having the Jaeger::Encoder convert all strings to UTF-8 before they're converted into thrift format. Is there appetite for this?

The performance impact (extra object allocations and CPU) of doing this is hard to justify. I would rather we track down which instrumentation is adding binary string values, and fix it.

**Comment by chrisholmes** [comment]
Yes, I think that’s a fair point. 

With regards to tracking down the instrumentation, my team’s made a change in the last couple days that moved the Kafka consumer onto a different Kafka topic and we’ve not seen the error since. This means that we’ll not be able to do any debugging using real data, but it does point to the Kafka instrumentation having a potential gap in its instrumentation. 

We’re using `#each_message` from the `Kafka::Consumer` and we’re not adding any custom attributes to the spans. From what I can tell there should only be two String values added to the Span from the message, the `topic` and the `key`. I suppose other values could be strings that haven’t been coerced into integers, as the instrumentation isn’t attempting this, but I’m struggling to see how this would happen without ruby_kafka or something else in the stack misbehaving.

I do have a remaining concern: My understanding is that the exporter is currently serializing the spans in batch and the encoding error will cause valid spans that have been batched with the span that contains the binary string to be dropped. Is that a valid concern? Would adding some `rescue` and debug logging help? I’m assuming that the logging could report on which instrumentation library has the error.

**Comment by fbogsany** [comment]
> I do have a remaining concern: My understanding is that the exporter is currently serializing the spans in batch and the encoding error will cause valid spans that have been batched with the span that contains the binary string to be dropped. Is that a valid concern? Would adding some `rescue` and debug logging help? I’m assuming that the logging could report on which instrumentation library has the error.

The error is raised inside generated code for the Thrift encoding. We already log the error, but it likely doesn't have enough information to figure out which attribute, span or instrumentation caused the problem: https://github.com/open-telemetry/opentelemetry-ruby/blob/7eed08a570a859feaae76a01af556c1557bf89c6/exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb#L45-L53

You can replace the default `OpenTelemetry.error_handler` if you want to try to dig out more details. The default is https://github.com/open-telemetry/opentelemetry-ruby/blob/7eed08a570a859feaae76a01af556c1557bf89c6/api/lib/opentelemetry.rb#L33-L37
