### ISSUE TITLE
Add CI, either Circle or Travis

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#77]
We have a `.travis.yml` that *should* enable TravisCI for this project, but actually turning it on requires admin access to Travis (or to the open-telemetry org on Github - I'm not clear which). None of the primary contributors to this project have that access.

@SergeyKanzhelev or @bogdandrutu can you please enable this?

Alternatively, if the preference is to use CircleCI, can you please enable it there and I'll add the necessary config.

**Comment by fbogsany** [comment]
Ping. Would love some help with this!

**Comment by rdooley** [comment]
This would be very nice to have
