### ISSUE TITLE
Clarify `Baggage` metadata exposure

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#791]
Although `Baggage` entry metadata is not used extensively these days, in the future we will need to use/expose this.  Just wanted to clarify that this has been taken into account for the mid term future (it sounds like you _did_ but wanted to double verify anyway).

Probably `Manager.raw_entries()` will in the future become public, or you will add a `Manager.value_full()` or similar function?

**Comment by fbogsany** [comment]
It is likely that we'll expose `Manager.raw_entries()` in the future. The API does not yet specify a mechanism to access the metadata, however we require it for the default (W3C) text map propagator, so we chose to tag `raw_entries` as `@api private` until an appropriate operation is added to the spec.

**Comment by carlosalberto** [comment]
Makes sense! Thanks!
