### ISSUE TITLE
SDK: post-request vs immediate export

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#8]
The [OpenCensus gem](https://github.com/census-instrumentation/opencensus-ruby) buffers spans during a request (for Rack apps) and exports them when the request has completed. This means finished child spans of long requests will not be available for analysis until the request finishes.

Should we wait for request completion to export all child spans, or should spans be exported as they finish?

**Comment by benedictfischer09** [comment]
I would think the agent should operate in its own thread or process and have no knowledge of the thread that generated the span, whether that is a http request or some other process like a background job.  As spans are placed onto the buffer in the agent thread it should have some strategy for flushing the buffer, probably a combination of hitting a max number of messages or a max time delay.

**Comment by fbogsany** [comment]
The spec is clear on non blocking requirements around span export. The supporting mechanism will be BatchSampledSpanProcessor, for exporters that want to export batches asynchronously.
