### ISSUE TITLE
Consider removing HttpToStatus from API/core

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#809]
https://github.com/open-telemetry/opentelemetry-ruby/blob/main/api/lib/opentelemetry/trace/util/http_to_status.rb defines util logic around http codes, which is logically closer to instrumentation, which in turn is not yet stable. Consider removing it from the core package and putting it in a contrib/extra one.

**Comment by fbogsany** [comment]
👍 it's incorrect anyway. I'll remove it altogether in #805.
