### ISSUE TITLE
SDK: implement metrics when OTEPs are approved

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#81]
See #80 for API side of this.

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/259 metrics SDK spec moved to Alpha 0.3.

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/347

**Comment by genebean** [comment]
What's the status of this?

**Comment by ioquatix** [comment]
I'm also interested in this :) it would be amazing!

**Comment by fbogsany** [comment]
The spec is currently in “Feature Freeze” state, but is still considered Experimental. We may be able to proceed with the API, but the SDK spec is still WIP.

**Comment by beanieboi** [comment]
as of https://github.com/open-telemetry/opentelemetry-specification/pull/2104 the Metrics API moved to stable.

**Comment by fbogsany** [comment]
As of #1004 we implemented an initial version of the Metrics API 😛

**Comment by fbogsany** [comment]
Note that this issue is about the SDK rather than the API. The SDK spec for metrics is in "feature freeze" and we're starting the implementation in #1108.

**Comment by fbogsany** [comment]
#1108 is continuing in fits & starts. I suggest following that PR for status updates.
