### ISSUE TITLE
Verify that no Baggage is stored in Context upon empty data

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#811]
When extracting `Baggage`, if the related baggage header is empty (no value or empty string), the `Context` should be returned untouched. This is done so unnecessary allocations happen for this (relatively common) scenario.

**Comment by ahayworth** [comment]
I spoke to @ericmustin and offered to take care of this, since I had a little more bandwidth, and he agreed.
