### ISSUE TITLE
Consider making NoopTextMapPropagator private

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#812]
https://github.com/open-telemetry/opentelemetry-ruby/blob/main/api/lib/opentelemetry/context/propagation/noop_text_map_propagator.rb can probably be defined as private, and be enabled public later on if/as needed. This is done to reduce API surface ;)

**Comment by fbogsany** [comment]
We reference this in two places in the API and once in the SDK. Ruby doesn't provide a mechanism to make this private to the API. We could mark it with the comment `@api private`, but then we're technically violating that by using it from the SDK. We can get around that with some duplication.

So, you're not wrong 😄 but we'll have to jump through some hoops to make it so.

**Comment by ahayworth** [comment]
I think this is fixed by #841 - I just copied and pasted the implementation into the SDK so that we could have a "private" implementation in the API where needed (not that anything is ever really private in Ruby, of course...).
