### ISSUE TITLE
Consider hiding `TracerProvider.stopped`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#815]
We don't offer this in other SIGs, and unless it's really required by some components, we could hide it (at least for now).

**Comment by fbogsany** [comment]
As with `active_span_processor`, we currently access `TracerProvider.stopped` from `Tracer.internal_create_span`. We can mark it `@api private` for now, and if we decide to move `internal_create_span` to `TracerProvider`, we can remove it entirely.
