### ISSUE TITLE
Consider hiding `TracerProvider.active_span_processor`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#816]
Similarly to `TracerProvider.stopped`, we don't offer/expose this and I think it's rather dangerous to allow users to consume it.

**Comment by fbogsany** [comment]
We can mark this `@api private`. We need it at the moment for `Tracer.internal_create_span`. There's an argument to be made for moving `internal_create_span` to the SDK's `TracerProvider` and marking that `@api private`, at which point we would not need to expose `stopped` or `active_span_processor`.
