### ISSUE TITLE
SDK: integration tests

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#82]
We need integration tests in the SDK gem to exercise the integration between the API and the SDK. A good structure for this is probably a method that, for example, traces a bunch of operations in different ways (root spans, child-of-remote spans, child-of-local spans, with and without links, etc.), and then a bunch of tests that configure the global tracer in different ways, call the tracing method, and asserts the results using an `InMemorySpanExporter`.

**Comment by fbogsany** [comment]
This will also serve to explore the ergonomics of the API.

**Comment by rdooley** [comment]
I'll take a shot at this one

**Comment by rdooley** [comment]
EDIT: on second thought this is perhaps better left until further unittesting is in place

**Comment by duonoid** [comment]
I can work on this.
