### ISSUE TITLE
Remove, move or hide MultiSpanExporter and MultiSpanProcessor

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#825]
`MultiSpanProcessor` and `MultiSpanExporter` are not required by the specification. `MultiSpanExporter` is not referenced within the SDK, and has dubious value (other than perhaps debugging in production by tee-ing the spans to the console). `MultiSpanProcessor` is an implementation detail in `TracerProvider` that tries to remove a level of indirection for the common case of a single span processing and export pipeline (at the cost of an extra level of indirection for multiple pipelines).

Should we remove `MultiSpanExporter`, or move it to a convenience gem?

Should we remove `MultiSpanProcessor` or hide it as an implementation detail in `TracerProvider`? It is highly unlikely that the extra level of indirection (`TracerProvider -> array -> SpanProcessor` vs `TracerProvider -> SpanProcessor`) is measurable compared with the encoding overhead, for example. Removing `MultiSpanProcessor` will likely simplify the implementation of `TracerProvider` and reduce the surface area of the SDK.

**Comment by robertlaurin** [comment]
>MultiSpanExporter is not referenced within the SDK, and has dubious value (other than perhaps debugging in production by tee-ing the spans to the console).

I think something like this is better served as an example of how you can implement your own custom exporter, but agree it should probably not live in the sdk.  

Did you envision this convenience gem to be more generic, or a collection export specific code? (Would the in memory span exporter live here too?)

>Removing MultiSpanProcessor will likely simplify the implementation of TracerProvider and reduce the surface area of the SDK.

I'm sold :)

**Comment by fbogsany** [comment]
> Would the in memory span exporter live here too?

The spec says we should provide an in-memory exporter, so no, that stays in the SDK (likewise with the console exporter).

> Did you envision this convenience gem to be more generic, or a collection export specific code?

Excellent question! 😄
