### ISSUE TITLE
SDK: test exporters and processors

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#84]
Empty tests:
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/noop_span_processor_test.rb
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/multi_span_processor.rb (file misnamed)
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/export/in_memory_span_exporter_test.rb
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/export/multi_span_exporter_test.rb
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/export/noop_span_exporter_test.rb
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/export/simple_sampled_span_processor_test.rb

Note that https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/test/opentelemetry/sdk/trace/export/batch_sampled_span_processor_test.rb will be implemented in #74

**Comment by sveiss** [comment]
I'm going to make a start on this today.
