### ISSUE TITLE
OTLP exporter is based on very old proto version

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-ruby#846]
The OTLP exporter is based on v0.4.0, which was released in June 2020. The current version of the protocol v0.9.0 includes a lot of changes, especially for metrics.

**Comment by fbogsany** [comment]
We don't have any support in this project for Metrics (yet). AFAIK no significant changes have been made to the protocol w.r.t. Tracing, with the possible exception of semantic convention schema support. I propose to bump the proto when we implement that support.

**Comment by fbogsany** [comment]
This is the one addition we need: https://github.com/open-telemetry/opentelemetry-ruby/blob/e47910985222db46b4f4bd5b467336abbf794068/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L322-L326

We have until Oct 22, 2021 to update this: https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/trace/v1/trace.proto#L299-L305

I'll bump this 🔜 to set us up for the schema support. It is lower priority than 🚢 1.0, though.

**Comment by MikeGoldsmith** [comment]
Hey @fbogsany  - I've updated the proto files in #850. There was a breaking change between the version used by the exporter (0.4.0) and 0.5.0 when the tracing definition was marked as stable. This was to do with the the Status to StatusCode enums.

FYI the exporter can still export spans without the updated proto files but spans have a status_code of 0 (unspecified) where after updating the status code is set correctly.

**Comment by fbogsany** [comment]
> Hey @fbogsany - I've updated the proto files in #850. There was a breaking change between the version used by the exporter (0.4.0) and 0.5.0 when the tracing definition was marked as stable. This was to do with the the Status to StatusCode enums.
> 
> FYI the exporter can still export spans without the updated proto files but spans have a status_code of 0 (unspecified) where after updating the status code is set correctly.

Thanks. The restrictions were understood. See my previous comment https://github.com/open-telemetry/opentelemetry-ruby/issues/846#issuecomment-871045387. I'll have to take a close look at the change, but I'm prioritizing work required for 1.0 at the moment. Thanks again for your contribution, though.

**Comment by MikeGoldsmith** [comment]
@fbogsany would a 1.0 not require to use at least the v0.5.0 proto spec which marks the tracing definition as stable? The currently used 0.4.0 version has the tracing definitions marked as Beta, plus has a definition change for SpanKind and StatusCode.

I can update my PR to bump to a version between 0.5.0 and 0.8.0 if you prefer not to go to the latest.

**Comment by fbogsany** [comment]
> @fbogsany would a 1.0 not require to use at least the v0.5.0 proto spec which marks the tracing definition as stable? The currently used [0.4.0](https://github.com/open-telemetry/opentelemetry-proto/blob/v0.4.0/README.md) version has the tracing definitions marked as Beta, plus has a definition change for SpanKind and StatusCode.

AFAIK it isn't required to move to 1.0. We have been using OTel Ruby in production with OTLP and with the collector for some time without compatibility issues. The definition change for SpanKind has no impact on the wire representation. The StatusCode change has a clear deprecation period.

> I can update my PR to bump to a version between 0.5.0 and 0.8.0 if you prefer not to go to the latest.

The substance of the changes, as they affect functionality currently used, will be the same between these versions. We're apprehensive because we *do* use this in production and we'd like to increase our confidence in the change before we merge it. That simply means we're going to review it closely, including running integration tests & probably testing it in production before giving it a 👍

**Comment by MikeGoldsmith** [comment]
Hey @fbogsany - I just wanted to check back in to say I've done some more testing and found that the change in OTLP spec protocol does not affect ingestion. I thought that status code wasn't being read correctly, but I think that's something else.

In that case, I agree this is a lower priority but I do think it would be nice to bump the OTLP spec to at least v0.5.0 before the 1.0 release when it's marked officially stable.

**Comment by fbogsany** [comment]
Hey @MikeGoldsmith - sorry for the slightly cranky tone earlier. You caught me on a bad day 😞. Thanks for the contribution. I'd still like to do some integration testing locally, and ideally in (or close to) production before we 👍 and merge. The exporter won't be part of the 1.0 release (only the API and SDK gems will be marked 1.0.0), so there's no rush, but I'll try to get to this sometime this week 🤞 .
