### ISSUE TITLE
Exporters: implement Prometheus exporter

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#88]

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/259 metrics SDK spec moved to Alpha 0.3, so moving the exporter as well.

**Comment by pinglamb** [comment]
I am trying to study this but not sure how to begin.

I have a few questions in mind:

* Is the metric api implementation ready?
* So with the prometheus exporter, does it mean that we have to map the OpenTelemetry entities (counter, measure, ...) to corresponding prometheus implementations (counter, gauge, ...)?
* How do library users specify that they want to use prometheus exporter, through some sort of configuration?
* From my understanding, prometheus expects metric provider to expose http endpoint for scraping, so how should we hook that up with rack servers using this library, as a middleware?

**Comment by fbogsany** [comment]
We don’t yet have an implementation of Metrics in the SDK. We need that before we can start work on a Prometheus (or statsd) exporter.
