### ISSUE TITLE
HTTP Response Headers

### ISSUE THREAD

**Issue by krak3n** [open-telemetry/opentelemetry-ruby#886]
Hi!

It seems that the propagator HTTP headers are not returned on a HTTP response, for example when using the B3 propagator I would expect the `X-B3-*` headers to be returned on the response, using the Rack example code:

```ruby
require 'rubygems'
require 'bundler/setup'
require 'opentelemetry-sdk'
require 'opentelemetry-propagator-b3'

Bundler.require

ENV['OTEL_TRACES_EXPORTER'] = 'console'
OpenTelemetry::SDK.configure do |c|
  c.use 'OpenTelemetry::Instrumentation::Rack'

  c.propagators = [OpenTelemetry::Propagator::B3::Multi.text_map_propagator]
end

builder = Rack::Builder.app do
  use OpenTelemetry::Instrumentation::Rack::Middlewares::TracerMiddleware

  app = ->(_env) { [200, { 'Content-Type' => 'text/plain' }, ['All responses are OK']] }
  run app
end

puts Rack::MockRequest.new(builder).get('/').headers
```

The output headers are:

```
{"Content-Type"=>"text/plain"}
```

However I would expect to see the `X-B3-TraceId` headers on the response.

This is how the Go application libraries function, for example:

```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/contrib/propagators/b3"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/stdout/stdouttrace"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/trace"
)

var propagator propagation.TextMapPropagator = b3.B3{
	InjectEncoding: b3.B3MultipleHeader,
}

func main() {
	exporter, err := stdouttrace.New(stdouttrace.WithPrettyPrint())
	if err != nil {
		fmt.Println(err)
		return
	}

	tp := trace.NewTracerProvider(
		trace.WithSampler(trace.AlwaysSample()),
		trace.WithBatcher(exporter),
	)

	otel.SetTracerProvider(tp)

	handler := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Write([]byte("hello world"))
	})

	srv := httptest.NewServer(otelhttp.NewHandler(handler, "test-service",
		otelhttp.WithPropagators(propagator)))

	rsp, err := srv.Client().Get(srv.URL)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(rsp.Header)

	srv.Close()
}
```

Returns these HTTP headers:

```
map[Content-Length:[11] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 22 Jul 2021 15:49:01 GMT] X-B3-Sampled:[1] X-B3-Spanid:[f80087fe85581783] X-B3-Traceid:[80de0d29cd110868f3aa776b8638a327]]
```

Is it possible to obtain the same behaviour with the ruby propagators?

I noticed the B3 propagator dosen't seem to implement the inject method and also I couldn't see in the Rack middleware for example that the propagators inject method is called after the request is handled, for example this happens in go here: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/1fd74e9012b1bbe24b37d9da88791e618b297e64/instrumentation/net/http/otelhttp/wrap.go#L94

As you can probably tell I am not a ruby engineer so forgive me if I am being stupid 😂

**Comment by arielvalentin** [comment]
@krak3n We will have to take a look to confirm but I am not aware of something in the specification that requires server responses to include context propagation information since it isn't continuing the request to a downstream system although I do see how this would be helpful for debugging. 

Would you happen to know if it is required by the spec?

**Comment by krak3n** [comment]
@arielvalentin I'm not sure if it is part of the spec of if the go otel libs are the anomaly vs the other otel lanuage libs.

Our use case us for debugging and for usage in our synthetic tests so we don't have to generate trace ids and rely on on the trace ids automatically generated when new requests come in.

**Comment by fbogsany** [comment]
Go is an anomaly here. For HTTP, context injection is expected only to occur on the client side into outgoing request headers, and context extraction is expected only to occur on the server side from incoming request headers. There is no expectation that context will be injected into *response* headers - I believe this is a mistake in the Go HTTP instrumentation, but it predates inclusion in the `-contrib` repo.

**Comment by krak3n** [comment]
ok thank you @fbogsany I'll close this issue :+1:
