### ISSUE TITLE
Exporters: implement OpenTelemetry protocol exporter

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#89]

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/oteps/blob/master/text/0059-otlp-trace-data-format.md

**Comment by mwear** [comment]
It looks like the protos have been declared for beta: https://github.com/open-telemetry/opentelemetry-proto/pull/103

**Comment by fbogsany** [comment]
Cool. Testing this is gated on https://github.com/open-telemetry/opentelemetry-collector/pull/577 but we can start implementation.

**Comment by fbogsany** [comment]
https://github.com/open-telemetry/oteps/blob/master/text/0099-otlp-http.md describes the protocol over HTTP instead of gRPC. We might consider doing this first, since it avoids pulling in a dependency on gRPC.

https://github.com/open-telemetry/opentelemetry-collector/pull/577 is merged, so this is unblocked.
