### ISSUE TITLE
instrumentation-base: Support enums as an option 

### ISSUE THREAD

**Issue by ahayworth** [open-telemetry/opentelemetry-ruby#898]
Currently we typically validate "enum-like" options as a callable, like so:

```ruby
option :foo, default: :bar, validate: ->(opt) { %i[bar baz].include?(opt) }
```

Instead, it'd be nice to support an enum option. Perhaps something like:

```ruby
option :foo, default: :bar, validate: =[:bar, :baz]
```

**Comment by ericmustin** [comment]
addressed by https://github.com/open-telemetry/opentelemetry-ruby/pull/994
