### ISSUE TITLE
SDK: auto-instrumentation via ActiveSupport::Notification

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#9]
ActiveSupport::Notification is a common mechanism for instrumenting a Rails application. Its API is a bit of a mess, though. For example, the `payload` can be modified by subscribers, and between calls to `start` and `finish`, so care has to be taken to only copy attributes from the `payload` in `finish`. Also, calls to `start` may not be paired with calls to `finish` if (another) subscriber raises an error.

Given the complexity of the API, should we support or use it for auto-instrumentation, or rely on lower-level monkey-patching?

**Comment by indrekj** [comment]
I don't think this library itself should depend directly on the activesupport library. I'd rather see sepate gems that allow adding instrumentation support for different libraries using this library. E.g. In open tracing case I made a [ruby-activerecord-opentracing](https://github.com/salemove/ruby-activerecord-opentracing) library which can be used to add instrumentation support for activerecord which uses activesupport. The tracing client itself doesn't know anything about ActiveRecord / ActiveSupport / Rails.

**Comment by fbogsany** [comment]
We've had a lot of success with auto-instrumentation of all common frameworks and services at Shopify, in our internal tracing gem. This can be accomplished without adding unused gems as dependencies. The trick is to rescue load errors from the adapters. Our initializer looks like:

```ruby
%i(dalli memcached net_http rack rack_error redis resque_like resque sidekiq panama graphql).each do |adapter|
  require "shopify/tracing/adapters/#{adapter}_adapter"
rescue LoadError
end
```

**Comment by benedictfischer09** [comment]
I agree with @indrekj that keeping the OpenTelemetry sdk and instrumentation libraries as separate projects is a good idea.  I could definitely imagine a popular gem that provides the auto-instrumentation you are suggesting @fbogsany many people would probably find it useful

**Comment by fbogsany** [comment]
#19 subsumes the registration aspects of this issue. We won’t take a dependency on ActiveSupport in the API or SDK gems. I think this issue is out of scope for this project.
