### ISSUE TITLE
Implement OpenCensus compatibility shim

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#90]
Note that the OpenCensus implementation for Ruby was incomplete - in particular, it lacked metrics and exporter support. Do we need to implement an OC shim? Does it need to support metrics?

**Comment by yelcat** [comment]
+1 Need OpenCensus compatibility shim for java

**Comment by johnnyshields** [comment]
@fbogsany What's the real-world justification for this? Who is only supporting OpenCensus but not OpenTelemetry?

**Comment by fbogsany** [comment]
This is more complicated than opentracing. OpenCensus for Ruby never progressed beyond Alpha. There is a tracking issue for the compatibility shim here: https://github.com/open-telemetry/opentelemetry-specification/issues/1175. It is not clear whether we need to implement one for Ruby.
