### ISSUE TITLE
Implement OpenTracing compatibility shim

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#91]

**Comment by rdooley** [comment]
👋 I'm your huckleberry.

Self link https://github.com/open-telemetry/opentelemetry-java/tree/master/opentracing_shim

**Comment by fbogsany** [comment]
The initial PR is #108 , however I don't believe @rdooley has time to continue with this and the PR likely needs significant updates to account for drift in the API. I've removed the assignment & opened this up to other folks who might like to help out.

**Comment by fbogsany** [comment]
Note also https://github.com/open-telemetry/opentelemetry-specification/pull/768 adds clarity around requirements here.

**Comment by rdooley** [comment]
> The initial PR is #108 , however I don't believe @rdooley has time to continue with this and the PR likely needs significant updates to account for drift in the API. I've removed the assignment & opened this up to other folks who might like to help out.

That is exactly correct. Thank you for removing my assignment.

**Comment by fbogsany** [comment]
Pushing this out until https://github.com/open-telemetry/opentelemetry-specification/pull/768 is approved.

**Comment by johnnyshields** [comment]
@fbogsany What's the real-world justification for this? Who is only supporting OpenTracing but not OpenTelemetry?

**Comment by fbogsany** [comment]
A compatibility shim is required by the spec, although that requirement is implicit for now. There’s a tracking issue here: https://github.com/open-telemetry/opentelemetry-specification/issues/1174
