### ISSUE TITLE
Cannot install opentelemetry-instrumentation-all 0.20.1 

### ISSUE THREAD

**Issue by looneym** [open-telemetry/opentelemetry-ruby#926]
**Description of the bug**

Attempting to install `opentelemetry-instrumentation-all` at `0.20.1` fails:

```
Bundler could not find compatible versions for gem "opentelemetry-instrumentation-sidekiq":
  In Gemfile:
    opentelemetry-instrumentation-all (= 0.20.1) was resolved to 0.20.1, which depends on
      opentelemetry-instrumentation-sidekiq (~> 0.20.0)

Could not find gem 'opentelemetry-instrumentation-sidekiq (~> 0.20.0)', which is required by gem 'opentelemetry-instrumentation-all (= 0.20.1)', in any of the sources.
```

This can be reproduced with this minimal Gemfile:

```Gemfile
source 'https://rubygems.org'
ruby   '2.5.5'
gem 'opentelemetry-instrumentation-all', '0.20.1'
```

It seems v0.20.0 of the sidekiq instrumentation did not make it to Rubygems as it is not present here:  https://rubygems.org/gems/opentelemetry-instrumentation-sidekiq

**Comment by robertlaurin** [comment]
Thanks for the report, 0.20.0 for sidekiq is released now.
https://rubygems.org/gems/opentelemetry-instrumentation-sidekiq

Going to close this issue, if you're still having trouble feel free to reopen it.
