### ISSUE TITLE
Add support for `with_parent` to `in_span`?

### ISSUE THREAD

**Issue by ioquatix** [open-telemetry/opentelemetry-ruby#936]
https://github.com/open-telemetry/opentelemetry-ruby/blob/cc28b8648e4085ff62e65e3db87ff45f82750cd1/api/lib/opentelemetry/trace/tracer.rb#L26

This would be very convenient.

**Comment by fbogsany** [comment]
We removed this parameter in #729. You can see the relevant discussion in #703.

**Comment by ioquatix** [comment]
Thanks for the clarification. It makes sense. I think if there was any action item, it would be adding a link to documentation explaining how to use `with_context` and how servers should handle external contexts.
