### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#94]
Automate or document build and release process (Rubygems, etc.)

**Comment by fbogsany** [comment]
Also release schedule, see Python for example: https://github.com/open-telemetry/opentelemetry-python#release-schedule

**Comment by dazuma** [comment]
@mwear I can start looking at this.

**Comment by fbogsany** [comment]
Do we want to publish API docs as well?

**Comment by dazuma** [comment]
Yeah I'll be looking into this this week. Tentative plan is to set up CI to push to Rubygems (after suitable automated testing and validating that the versions match, etc.) when a release tag is created in Github.

I'm not sure yet what the plan is for publishing reference docs. It looks like there's a page for it: https://opentelemetry.io/docs/ but there's no content yet.

**Comment by mwear** [comment]
Should we consider hosting docs at https://www.rubydoc.info?

**Comment by dazuma** [comment]
Docs will get there automatically after gems are published. But it seems like the intent is to host docs on opentelemetry.io also. I'll see if I can determine a process to push doc PRs over to the opentelemetry.io repo.

**Comment by dazuma** [comment]
Related issue (NodeJS release process) at https://github.com/open-telemetry/opentelemetry-js/issues/419

**Comment by dazuma** [comment]
This is done.
