### ISSUE TITLE
Documentation: publish API docs

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#95]
Docs are generated using YARD. How and where do we publish these?

API docs could also use a review pass for consistency, completeness and grammar.

**Comment by dazuma** [comment]
@mwear I can start looking at this.

**Comment by fbogsany** [comment]
Rely on Rubydoc for this. Add a link from OT.io docs.

**Comment by fbogsany** [comment]
Potentially also push our docs to the OT.io website.

**Comment by dazuma** [comment]
Will start looking at pushing docs to OT.io as part of the release process.

**Comment by fbogsany** [comment]
This is done AFAICT: https://www.rubydoc.info/gems/opentelemetry-api/0.2.0 and https://opentelemetry.io/docs/ruby/tracing/
