### ISSUE TITLE
obscure config error 

### ISSUE THREAD

**Issue by inductor** [open-telemetry/opentelemetry-ruby#951]
**Description of the bug**

Hi, I'm trying to use this plugin with rails and I get the following error but it looks very vague and not sure what's causing.

```
E, [2021-09-21T13:46:51.454756 #7] ERROR -- : OpenTelemetry error: unexpected configuration error due to uninitialized constant OpenTelemetry::Exporter - OpenTelemetry::SDK::ConfigurationError
```

My config is as follows

```ruby
OpenTelemetry::SDK.configure do |c|
    c.use 'OpenTelemetry::Instrumentation::Rails'
    c.use 'OpenTelemetry::Instrumentation::Mysql2'
    c.use 'OpenTelemetry::Instrumentation::Redis'
    c.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        exporter: OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: 'simplest-agent.observability', port: 6831)
      )
    )
    c.service_name = 'app'
    c.service_version = '0.1.0'
  end
```

I'm running this on EKS

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.2"
RUBY_DESCRIPTION: "ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]"

**Share a simplified reproduction if possible**

**Comment by arielvalentin** [comment]
@inductor could you share how you are loading your dependencies and requiring the exporter? 

E.g. Are you using a Gemfile + `Bundler.require`?

**Comment by inductor** [comment]
Hi @arielvalentin 
This is our changes https://github.com/cloudnativedaysjp/dreamkast/pull/859/files

I modified requires now, and got this error.

I think name resolve is working and so is my jaeger and now wondering what this error shows.

```
E, [2021-09-21T15:29:41.252817 #7] ERROR -- : OpenTelemetry error: unexpected configuration error due to exporter {:exporter=>#<OpenTelemetry::Exporter::Jaeger::AgentExporter:0x0000558abdd1ca70 @client=#<OpenTelemetry::Exporter::Jaeger::Thrift::Agent::Client:0x0000558abdd1c8e0 @iprot=#<Thrift::CompactProtocol:0x0000558abdd1c980 @trans=#<OpenTelemetry::Exporter::Jaeger::Transport:0x0000558abdd1ca48 @socket=#<UDPSocket:fd 6, AF_INET, 10.100.192.250, 41170>, @buffer=#<Thrift::MemoryBufferTransport:0x0000558abdd1c9f8 @buf="", @index=0>>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @oprot=#<Thrift::CompactProtocol:0x0000558abdd1c980 @trans=#<OpenTelemetry::Exporter::Jaeger::Transport:0x0000558abdd1ca48 @socket=#<UDPSocket:fd 6, AF_INET, 10.100.192.250, 41170>, @buffer=#<Thrift::MemoryBufferTransport:0x0000558abdd1c9f8 @buf="", @index=0>>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @seqid=0>, @max_packet_size=65000, @shutdown=false, @sizing_transport=#<OpenTelemetry::Exporter::Jaeger::AgentExporter::SizingTransport:0x0000558abdd1c890 @size=0>, @sizing_protocol=#<Thrift::CompactProtocol:0x0000558abdd1c868 @trans=#<OpenTelemetry::Exporter::Jaeger::AgentExporter::SizingTransport:0x0000558abdd1c890 @size=0>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @timeout=10.0>} does not appear to be a valid exporter - OpenTelemetry::SDK::ConfigurationError
```

**Comment by inductor** [comment]
I removed the `ENV` but error still is the same :|

```
E, [2021-09-21T16:51:33.000104 #7] ERROR -- : OpenTelemetry error: unexpected configuration error due to exporter {:exporter=>#<OpenTelemetry::Exporter::Jaeger::AgentExporter:0x000055701c1fa540 @client=#<OpenTelemetry::Exporter::Jaeger::Thrift::Agent::Client:0x000055701c1fa388 @iprot=#<Thrift::CompactProtocol:0x000055701c1fa450 @trans=#<OpenTelemetry::Exporter::Jaeger::Transport:0x000055701c1fa518 @socket=#<UDPSocket:fd 6, AF_INET, 10.100.187.247, 40161>, @buffer=#<Thrift::MemoryBufferTransport:0x000055701c1fa4a0 @buf="", @index=0>>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @oprot=#<Thrift::CompactProtocol:0x000055701c1fa450 @trans=#<OpenTelemetry::Exporter::Jaeger::Transport:0x000055701c1fa518 @socket=#<UDPSocket:fd 6, AF_INET, 10.100.187.247, 40161>, @buffer=#<Thrift::MemoryBufferTransport:0x000055701c1fa4a0 @buf="", @index=0>>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @seqid=0>, @max_packet_size=65000, @shutdown=false, @sizing_transport=#<OpenTelemetry::Exporter::Jaeger::AgentExporter::SizingTransport:0x000055701c1fa338 @size=0>, @sizing_protocol=#<Thrift::CompactProtocol:0x000055701c1fa2e8 @trans=#<OpenTelemetry::Exporter::Jaeger::AgentExporter::SizingTransport:0x000055701c1fa338 @size=0>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @timeout=10.0>} does not appear to be a valid exporter - OpenTelemetry::SDK::ConfigurationError
```

**Comment by arielvalentin** [comment]
@inductor I did not notice this before but it looks like you are using a keyword arg `exporter` however the [`BatchSpanExporter` uses a positional argument.](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb#L47) Remove the `exporter` keyword and try again:

In your snippet:
```ruby
    c.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        exporter: OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: 'simplest-agent.observability', port: 6831)
      )
    )
```

From the [guide](https://github.com/open-telemetry/opentelemetry-ruby/tree/main/exporter/jaeger#how-do-i-get-started): 
```ruby
    c.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
         OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: 'simplest-agent.observability', port: 6831)
      )
    )
```

**Comment by inductor** [comment]
@arielvalentin 
Oh thank you, the trace data is there now!

One question, the service name is "unknown_service" while I set the service name by `ENV['OTEL_SERVICE_NAME'] = 'dreamkast'
` and `tracer = OpenTelemetry.tracer_provider.tracer('dreamkast', '0.1.0')`. Are those not enough?

![image](https://user-images.githubusercontent.com/20236173/134445909-895dec69-12d9-4fb4-be30-595e47a81e4b.png)

**Comment by inductor** [comment]
`c.service_name = 'service_name'` did this, but I didn't see it in the guide.

**Comment by arielvalentin** [comment]
The `TracerProvider#tracer` method created a "named tracer". That sets the `instrumentation.name` and `instrumentation.versión` attributes and will not override the `service.name` and `service.versión`.

Looking at your PR you are both setting the environment variable `OTEL_SERVICE_NAME` and the `configurator.service_name`. You only have to set one or the other, however that does not explain why it appears as `unknown_service`.

**Comment by arielvalentin** [comment]
I see now. You are creating a tracer inside of the configure block. That ends up creating a tracer that is not properly configured. 

Create the tracer outside of the configure block.

**Comment by inductor** [comment]
@arielvalentin This approach works. thanks for your advice!

Btw I'm completely new to open telemetry and jeager, and I noticed that in the current setting I only see MySQL traces, but not app tracing in rails application while I have `c.use 'OpenTelemetry::Instrumentation::Redis'`. Do I have to make additional configurations for tracer? If there's a good reference that'd be great.

**Comment by arielvalentin** [comment]
@inductor My recommendation would be to start with enabling `instrumentation-all` and then disabling any instrumentation after that.

Please take a look at the quick start guide for more details: https://github.com/open-telemetry/opentelemetry-ruby/blob/main/website_docs/quick_start.md

Also I am going to convert this to a discussion since there is no bug to fix here.
