### ISSUE TITLE
Code examples: gRPC instrumentation example

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#96]

**Comment by fbogsany** [comment]
@mwear @dazuma no-one is currently working on this. Do we need it for the Alpha 0.2 release, or should we punt it to Alpha 0.3?

**Comment by mwear** [comment]
I don't think this should hold up our v0.2 alpha. I'm in favor of punting to Alpha 0.3.

**Comment by fbogsany** [comment]
@pinglamb can you please comment on this issue so that I can assign it to you?

**Comment by pinglamb** [comment]
@fbogsany 

I am working on this in https://github.com/open-telemetry/opentelemetry-ruby/pull/229
