### ISSUE TITLE
add schemaUrl support

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-ruby#969]
just adding to track work around SchemaUrl (from [opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go/issues/2209#issuecomment-908405634))

> The schema URL defines the version of semantic conventions used in resource. Each version of semantic conventions will export a unique schema URL that defines the form of the semantic conventions and the transforms to others.

Now that [OTEP-152](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5036) spec changes have been [added to the specification](https://github.com/open-telemetry/opentelemetry-specification/pull/1666) it would be useful to add for ruby.

There are a number of [use cases](https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md#use-cases) / benefits that impact instrumentations+resource detectors/processors/and backends. For end-users, many of these use cases can be adopted incrementally, ie, schemaUrl support can be added to span's emitted by instrumentation before it's added to a datastore or UI-layer for handling those spans.

For additional context, an example YAML file found by making a request to the schemaUrl is in the [OTEP's appendix](https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md#appendix-a-example-schema-file). OpenTelemetry-Go also contains an implementation. 

Also worth nothing that there's a [opentelemetry-collector-contrib issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5036) about the "transformation processor"  mentioned in the OTEP , and that processor work isn't started as far as i can tell.  Of course, it's possible to do the "span transformation processor"-ing via either a custom library that manipulates span/metric/log/event and resource processors yaml config, or via backend custom processing. It would be nice to see standard tooling be written here of course, but not blocking as far I can tell from having schemaUrl supported in opentelemetry-ruby.

**Comment by arielvalentin** [comment]
@ericmustin Does this mean that we need all of the auto-instrumenation to emit attributes locked to a certain schema?

To also include some constrains around what minimal semantic conventions schema version the instrumentation and SDK are emitting, unless we intend to support normalizing all fields starting from the earliest version of the schema. 

WDYT?

**Comment by ericmustin** [comment]
@arielvalentin Re: 
> Does this mean that we need all of the auto-instrumenation to emit attributes locked to a certain schema?

I think the technical answer currently is, Yes, but only if we want to add schema_url to an instrumentation (because these instrumentations are not 1.0) 

This behavior is indeed a bit constrainting, and imo, i think specified incorrectly in it's current form. Some other community has recognized this as well, see: https://github.com/open-telemetry/opentelemetry-go/issues/2341

It's unclear what the next steps are for this feature, I think they're trying to determine what the merge behavior ought to be, where that ought to happen, and how to determine whats _mergeable_ and what isn't.

For now I think we should just make sure we have schema_url support in our api/sdk and export, but not necessarily populate it ootb since in practice this will create lots of Resource.merge errors.

**Comment by ahayworth** [comment]
I added schema url support in #1237, although I didn't bother adding it to any instrumentation.

> It's unclear what the next steps are for this feature, I think they're trying to determine what the merge behavior ought to be, where that ought to happen, and how to determine whats mergeable and what isn't.

The resolution was "implementation dependent" 😆 - see the PR for how I chose to resolve it, we can do whatever we think is right in this instance.
