### ISSUE TITLE
Exporters for Google Cloud Trace and Google Cloud Monitoring

### ISSUE THREAD

**Issue by dazuma** [open-telemetry/opentelemetry-ruby#980]
This is a placeholder feature request for direct exporters to these two services. This may be moved to a different repo if we end up doing the development separately, but I'm putting it here in the interim.

**Comment by KaoruDev** [comment]
I was looking into using the [google-cloud-trace](https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-trace) and love that it works with Rails out of the box but it doesn't support things like Redis, like this project. How can I get the best of both worlds?

**Comment by arielvalentin** [comment]
@KaoruDev one option you may have is to use an OpenTelemetry collector and configure it to use the Google Cloud Exporter:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/googlecloudexporter/README.md
