### ISSUE TITLE
net_http instrumentation not following semantic conventions for net.peer.name

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-ruby#998]
**Description of the bug**
Spans created from `net_http` instrumentations are [started with attribute `peer.hostname` and `peer.port`](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb#L28) which are not in the specification. They should be changed to `net.peer.name` and `net.peer.port` [according to the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes)

If it's not intentionally, I can submit a PR with a fix

**Comment by arielvalentin** [comment]
Thanks for finding this. Contributions are always welcome!

**Comment by fbogsany** [comment]
Looks like these were added recently (at least for HTTP instrumentation) in https://github.com/open-telemetry/opentelemetry-specification/pull/1916
